// @generated by fresnel from registry.toml. Do not edit. Run `make features`.

use crate::core::Epoch;
use crate::fork::ForkName;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum FeatureId {}

impl FeatureId {
    /// All features, in registry order.
    pub const ALL: &'static [FeatureId] = &[];

    pub fn name(self) -> &'static str {
        match self {}
    }

    /// The first fork that the feature can run on.
    pub fn min_fork(self) -> ForkName {
        match self {}
    }
}

/// The fork version and fork epoch of each feature.
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
#[derive(Debug, Clone, PartialEq)]
pub struct FeatureSpec {}

impl FeatureSpec {
    pub fn mainnet() -> Self {
        Self {}
    }

    pub fn minimal() -> Self {
        Self {}
    }

    pub fn gnosis() -> Self {
        Self {}
    }

    pub fn fork_version(&self, id: FeatureId) -> [u8; 4] {
        match id {}
    }

    pub fn fork_epoch(&self, id: FeatureId) -> Option<Epoch> {
        match id {}
    }
}

/// The config keys of each feature.
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct FeatureConfig {}

impl FeatureConfig {
    pub fn from_spec(_spec: &FeatureSpec) -> Self {
        Self {}
    }

    /// Set the fork epochs of `spec`, and each fork version that the config has.
    pub fn apply_to(&self, _spec: &mut FeatureSpec) {}
}
