// @generated by fresnel from registry.toml. Do not edit. Run `make features`.

use super::{Feature, optional_fork_version};
use crate::core::{Epoch, deserialize_fork_epoch, serialize_fork_epoch};
use crate::fork::ForkName;
use serde::{Deserialize, Serialize};
use serde_utils::quoted_u64::MaybeQuoted;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum FeatureId {
    Eip8198,
}

impl FeatureId {
    /// All features, in registry order.
    pub const ALL: &'static [FeatureId] = &[FeatureId::Eip8198];

    pub fn name(self) -> &'static str {
        match self {
            FeatureId::Eip8198 => "eip8198",
        }
    }

    /// The first fork that the feature can run on.
    pub fn min_fork(self) -> ForkName {
        match self {
            FeatureId::Eip8198 => ForkName::Heze,
        }
    }
}

pub struct Eip8198;

impl Feature for Eip8198 {
    const ID: FeatureId = FeatureId::Eip8198;
    const MIN_FORK: ForkName = ForkName::Heze;
}

/// The fork version and fork epoch of each feature.
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
#[derive(Debug, Clone, PartialEq)]
pub struct FeatureSpec {
    pub eip8198_fork_version: [u8; 4],
    /// `None` means that the feature never activates.
    pub eip8198_fork_epoch: Option<Epoch>,
}

impl FeatureSpec {
    pub fn mainnet() -> Self {
        Self {
            eip8198_fork_version: [0xe8, 0x19, 0x80, 0x00],
            eip8198_fork_epoch: None,
        }
    }

    pub fn minimal() -> Self {
        Self {
            eip8198_fork_version: [0xe8, 0x19, 0x80, 0x01],
            eip8198_fork_epoch: None,
        }
    }

    pub fn gnosis() -> Self {
        Self {
            eip8198_fork_version: [0xe8, 0x19, 0x80, 0x64],
            eip8198_fork_epoch: None,
        }
    }

    pub fn fork_version(&self, id: FeatureId) -> [u8; 4] {
        match id {
            FeatureId::Eip8198 => self.eip8198_fork_version,
        }
    }

    pub fn fork_epoch(&self, id: FeatureId) -> Option<Epoch> {
        match id {
            FeatureId::Eip8198 => self.eip8198_fork_epoch,
        }
    }
}

/// The config keys of each feature.
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct FeatureConfig {
    #[serde(
        rename = "EIP8198_FORK_VERSION",
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_fork_version"
    )]
    pub eip8198_fork_version: Option<[u8; 4]>,
    #[serde(
        rename = "EIP8198_FORK_EPOCH",
        default,
        serialize_with = "serialize_fork_epoch",
        deserialize_with = "deserialize_fork_epoch"
    )]
    pub eip8198_fork_epoch: Option<MaybeQuoted<Epoch>>,
}

impl FeatureConfig {
    pub fn from_spec(spec: &FeatureSpec) -> Self {
        Self {
            eip8198_fork_version: Some(spec.eip8198_fork_version),
            eip8198_fork_epoch: spec.eip8198_fork_epoch.map(|value| MaybeQuoted { value }),
        }
    }

    /// Set the fork epochs of `spec`, and each fork version that the config has.
    pub fn apply_to(&self, spec: &mut FeatureSpec) {
        if let Some(version) = self.eip8198_fork_version {
            spec.eip8198_fork_version = version;
        }
        spec.eip8198_fork_epoch = self.eip8198_fork_epoch.map(|epoch| epoch.value);
    }
}
