[package]
name = "eth2_config"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2021"

[dependencies]
types = { path = "../../consensus/types" }
paste = "1.0.5"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.3"
reqwest = "0.11"
snap = "1.0.1"
