[package]
name = "lean_crypto"
version = "0.1.0"
authors = ["Eitan Seri-Levi <eitan@sigmaprime.io>"]
edition = { workspace = true }
rust-version = "1.93.0"

[dependencies]
lean_types = { workspace = true }
leansig_wrapper = { workspace = true }
rec_aggregation = { workspace = true }
tree_hash = { workspace = true }
