use std::path::Path;
use std::process::{Command, Output};

const REGISTRY: &str = r#"# Experimental consensus features.

[eip_toy]
min_fork = "Heze"
fork_version = { mainnet = "0xe0000000", minimal = "0xe0000001", gnosis = "0xe0000064" }

[eip_keep]
min_fork = "Gloas"
fork_version = { mainnet = "0xe1000000", minimal = "0xe1000001", gnosis = "0xe1000064" }
"#;

const CONSUMER: &str = r#"use types::features::{EipKeep, EipToy};

#[feature_dispatch(EipToy => features::eip_toy::reward, spec = spec, epoch = epoch)]
#[feature_dispatch(EipKeep => features::eip_keep::reward, spec = spec, epoch = epoch)]
pub fn reward(spec: &ChainSpec, epoch: Epoch) {}

#[feature_dispatch(
    EipToy => features::eip_toy::penalty,
    spec = spec,
    epoch = epoch
)]
pub fn penalty(spec: &ChainSpec, epoch: Epoch) {}

pub fn gate(spec: &ChainSpec, epoch: Epoch) -> bool {
    spec.feature_enabled::<EipToy>(epoch).is_some()
}
"#;

/// A copy of the parts of the workspace that `fresnel` reads, with the features `eip_toy` and
/// `eip_keep`.
fn workspace() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("temp dir");
    for (path, contents) in [
        (
            "consensus/types/src/fork/fork_name.rs",
            include_str!("../../consensus/types/src/fork/fork_name.rs"),
        ),
        (
            "fresnel/tests/fixtures/test_features.toml",
            include_str!("fixtures/test_features.toml"),
        ),
        ("consensus/types/src/features/registry.toml", REGISTRY),
        (
            "consensus/types/src/features/mod.rs",
            "mod generated;\npub mod eip_keep;\npub mod eip_toy;\n",
        ),
        (
            "consensus/types/src/features/eip_toy/mod.rs",
            "pub struct Config;\n",
        ),
        (
            "consensus/types/src/features/eip_keep/mod.rs",
            "pub struct Config;\n",
        ),
        (
            "consensus/state_processing/src/features/mod.rs",
            "pub mod eip_keep;\npub(crate) mod eip_toy;\n",
        ),
        (
            "consensus/state_processing/src/features/eip_toy/mod.rs",
            "pub fn reward(_active: Active<EipToy>) {}\n",
        ),
        (
            "consensus/state_processing/src/features/eip_keep/mod.rs",
            "pub fn reward(_active: Active<EipKeep>) {}\n",
        ),
        ("consensus/state_processing/src/lib.rs", CONSUMER),
    ] {
        let path = dir.path().join(path);
        std::fs::create_dir_all(path.parent().expect("parent")).expect("create dir");
        std::fs::write(path, contents).expect("write");
    }
    dir
}

fn fresnel(dir: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_fresnel"))
        .args(args)
        .current_dir(dir)
        .output()
        .expect("run fresnel")
}

fn git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .expect("run git")
        .status;
    assert!(status.success(), "git {args:?}");
}

fn read(dir: &Path, path: &str) -> String {
    std::fs::read_to_string(dir.join(path)).expect(path)
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

#[test]
fn generate_writes_the_footprint_of_each_feature() {
    let dir = workspace();
    let output = fresnel(dir.path(), &[]);
    assert!(output.status.success(), "{}", stderr(&output));

    assert_eq!(
        read(
            dir.path(),
            "consensus/types/src/features/eip_toy/FOOTPRINT.md"
        ),
        "<!-- @generated by fresnel. Do not edit. Run `make features`. -->\n\n\
         # `eip_toy` footprint\n\n\
         The lines outside the `features/eip_toy/` directories that name `EipToy` or `features::eip_toy`:\n\n\
         - `consensus/state_processing/src/lib.rs`: \
         `#[feature_dispatch(EipToy => features::eip_toy::reward, spec = spec, epoch = epoch)]`\n\
         - `consensus/state_processing/src/lib.rs`: `EipToy => features::eip_toy::penalty,`\n\
         - `consensus/state_processing/src/lib.rs`: \
         `spec.feature_enabled::<EipToy>(epoch).is_some()`\n\
         - `consensus/state_processing/src/lib.rs`: `use types::features::{EipKeep, EipToy};`\n"
    );
    assert!(read(dir.path(), "consensus/types/src/features/generated.rs").contains("EipToy"));
    assert!(fresnel(dir.path(), &["--check"]).status.success());
}

#[test]
fn check_fails_on_drift_and_on_uses_outside_the_gates() {
    let dir = workspace();
    assert!(fresnel(dir.path(), &[]).status.success());

    let consumer = dir.path().join("consensus/state_processing/src/lib.rs");
    std::fs::write(&consumer, format!("\n{CONSUMER}")).expect("write");
    let output = fresnel(dir.path(), &["--check"]);
    assert!(output.status.success(), "{}", stderr(&output));

    std::fs::write(
        &consumer,
        format!("{CONSUMER}pub fn off(spec: &ChainSpec, epoch: Epoch) -> bool {{\n    spec.feature_enabled::<EipToy>(epoch).is_none()\n}}\n"),
    )
    .expect("write");
    let output = fresnel(dir.path(), &["--check"]);
    assert_eq!(output.status.code(), Some(4));
    assert!(stderr(&output).contains("FOOTPRINT.md is out of date"));

    std::fs::write(
        &consumer,
        format!("{CONSUMER}pub fn id() -> FeatureId {{\n    FeatureId::EipToy\n}}\n"),
    )
    .expect("write");
    let output = fresnel(dir.path(), &[]);
    assert_eq!(output.status.code(), Some(1));
    let errors = stderr(&output);
    assert!(
        errors.contains("consensus/state_processing/src/lib.rs:18: `EipToy` outside"),
        "{errors}"
    );
    assert_eq!(errors.lines().count(), 1, "{errors}");
}

#[test]
fn delete_feature_removes_the_feature_and_lists_the_remaining_uses() {
    let dir = workspace();
    assert!(fresnel(dir.path(), &[]).status.success());
    git(dir.path(), &["init", "-q"]);
    git(dir.path(), &["add", "-A"]);
    git(
        dir.path(),
        &[
            "-c",
            "user.name=fresnel",
            "-c",
            "user.email=fresnel@example.com",
            "commit",
            "-q",
            "-m",
            "workspace",
        ],
    );

    let output = fresnel(dir.path(), &["--delete", "eip_toy"]);
    assert!(output.status.success(), "{}", stderr(&output));

    let registry = read(dir.path(), "consensus/types/src/features/registry.toml");
    assert!(!registry.contains("eip_toy"), "{registry}");
    assert!(registry.starts_with("# Experimental consensus features.\n\n[eip_keep]\n"));
    assert!(
        !dir.path()
            .join("consensus/types/src/features/eip_toy")
            .exists()
    );
    assert!(
        !dir.path()
            .join("consensus/state_processing/src/features/eip_toy")
            .exists()
    );
    assert!(
        dir.path()
            .join("consensus/state_processing/src/features/eip_keep")
            .exists()
    );
    assert_eq!(
        read(dir.path(), "consensus/types/src/features/mod.rs"),
        "mod generated;\npub mod eip_keep;\n"
    );
    assert_eq!(
        read(dir.path(), "consensus/state_processing/src/features/mod.rs"),
        "pub mod eip_keep;\n"
    );
    assert_eq!(
        read(dir.path(), "consensus/state_processing/src/lib.rs"),
        r#"use types::features::{EipKeep, EipToy};

#[feature_dispatch(EipKeep => features::eip_keep::reward, spec = spec, epoch = epoch)]
pub fn reward(spec: &ChainSpec, epoch: Epoch) {}

pub fn penalty(spec: &ChainSpec, epoch: Epoch) {}

pub fn gate(spec: &ChainSpec, epoch: Epoch) -> bool {
    spec.feature_enabled::<EipToy>(epoch).is_some()
}
"#
    );
    assert!(!read(dir.path(), "consensus/types/src/features/generated.rs").contains("EipToy"));
    assert_eq!(
        String::from_utf8_lossy(&output.stdout),
        "Deleted `eip_toy`. Remove the remaining uses of `EipToy`:\n\
         consensus/state_processing/src/lib.rs:1\n\
         consensus/state_processing/src/lib.rs:9\n"
    );
    assert!(fresnel(dir.path(), &["--check"]).status.success());
}

#[test]
fn delete_feature_rejects_an_unknown_feature() {
    let dir = workspace();
    let output = fresnel(dir.path(), &["--delete", "eip_nope"]);
    assert_eq!(output.status.code(), Some(1));
    assert!(stderr(&output).contains("has no feature `eip_nope`"));
}
