use fresnel::footprint::{Line, footprint, in_feature_dir, manifest, uses};

const CONSUMER: &str = r#"use types::features::{EipToy, FeatureId};
use types::{
    features::EipToy as Toy,
};

#[feature_dispatch(EipToy => features::eip_toy::reward, spec = spec, epoch = epoch)]
fn reward() {}

#[feature_dispatch(
    EipToy => features::eip_toy::long_reward,
    spec = spec,
    epoch = epoch
)]
fn long_reward() {}

fn gate(spec: &ChainSpec) {
    if spec.feature_enabled::<EipToy>(epoch).is_some() {}
    let epoch = spec.feature_fork_epoch(FeatureId::EipToy);
    let id = FeatureId::EipToy;
    let toy: EipToy = EipToy;
    let config = EipToyConfig::default();
    let other = spec.feature_enabled::<EipToyTwo>(epoch);
}
"#;

fn files() -> Vec<(String, String)> {
    vec![
        (
            "consensus/state_processing/src/features/eip_toy/mod.rs".to_string(),
            "pub fn reward(_active: Active<EipToy>) {}".to_string(),
        ),
        ("beacon_node/src/lib.rs".to_string(), CONSUMER.to_string()),
    ]
}

fn line(number: usize) -> Line {
    Line {
        path: "beacon_node/src/lib.rs".to_string(),
        number,
        text: CONSUMER
            .lines()
            .nth(number - 1)
            .map(|text| text.trim().to_string())
            .unwrap_or_default(),
    }
}

#[test]
fn feature_dirs() {
    assert!(in_feature_dir("features/eip_toy/mod.rs", "eip_toy"));
    assert!(in_feature_dir(
        "consensus/types/src/features/eip_toy/a/b.rs",
        "eip_toy"
    ));
    assert!(!in_feature_dir(
        "consensus/types/src/features/eip_toy.rs",
        "eip_toy"
    ));
    assert!(!in_feature_dir(
        "consensus/types/src/my_features/eip_toy/mod.rs",
        "eip_toy"
    ));
    assert!(!in_feature_dir(
        "consensus/types/src/features/eip_toy_two/mod.rs",
        "eip_toy"
    ));
}

#[test]
fn gates_dispatch_attributes_and_imports_are_allowed() {
    let footprint = footprint("eip_toy", "EipToy", &files());
    assert_eq!(
        footprint.touches,
        [line(1), line(3), line(6), line(10), line(17), line(18)]
    );
}

#[test]
fn other_uses_are_violations() {
    let footprint = footprint("eip_toy", "EipToy", &files());
    assert_eq!(footprint.violations, [line(19), line(20)]);
}

#[test]
fn a_dispatch_attribute_of_another_feature_is_a_violation() {
    let files = vec![(
        "src/lib.rs".to_string(),
        "#[feature_dispatch(Other => copy, spec = EipToy::spec(), epoch = epoch)]".to_string(),
    )];
    assert_eq!(
        footprint("eip_toy", "EipToy", &files).violations,
        [Line {
            path: "src/lib.rs".to_string(),
            number: 1,
            text: "#[feature_dispatch(Other => copy, spec = EipToy::spec(), epoch = epoch)]"
                .to_string(),
        }]
    );
}

#[test]
fn uses_lists_every_line_outside_and_inside_the_feature_dirs() {
    let lines = uses("EipToy", &files());
    assert_eq!(lines.len(), 9);
    assert_eq!(
        lines.first().map(|line| line.path.as_str()),
        Some("consensus/state_processing/src/features/eip_toy/mod.rs")
    );
}

#[test]
fn manifest_lists_the_touches_by_path_and_code_without_line_numbers() {
    let other_file = Line {
        path: "a/lib.rs".to_string(),
        number: 40,
        text: "use types::features::EipToy;".to_string(),
    };
    let same_code_elsewhere = Line {
        number: 99,
        ..line(17)
    };
    assert_eq!(
        manifest(
            "eip_toy",
            "EipToy",
            &[line(17), line(1), same_code_elsewhere, other_file]
        ),
        "<!-- @generated by fresnel. Do not edit. Run `make features`. -->\n\n\
         # `eip_toy` footprint\n\n\
         The lines outside the `features/eip_toy/` directories that name `EipToy`:\n\n\
         - `a/lib.rs`: `use types::features::EipToy;`\n\
         - `beacon_node/src/lib.rs`: `if spec.feature_enabled::<EipToy>(epoch).is_some() {}`\n\
         - `beacon_node/src/lib.rs`: `use types::features::{EipToy, FeatureId};`\n"
    );
}

#[test]
fn manifest_fences_code_with_backticks() {
    let touch = Line {
        path: "src/lib.rs".to_string(),
        number: 1,
        text: "// `EipToy` gate".to_string(),
    };
    assert!(
        manifest("eip_toy", "EipToy", &[touch])
            .ends_with("- `src/lib.rs`: `` // `EipToy` gate ``\n")
    );
}
