import LeanTypesProofs.Generated
import LeanTypesProofs.Spec
import LeanTypesProofs.Isqrt

/-!
# Correctness of Lighthouse's `Slot` justification rules

`Generated.lean` is generated by Aeneas from `lean/lean_types/src/slot.rs` in the Lighthouse
tree. `Spec.lean` states the leanSpec rules over natural numbers. This file proves that the two
Rust functions compute exactly those rules, for every pair of `u64` inputs, and never panic.
-/

namespace LeanTypesProofs

open Aeneas Aeneas.Std Aeneas.Std.WP Result lean_types

/-! ## Arithmetic -/

/-- If `r` is the integer square root of `d`, then `d` is a perfect square iff `r * r = d`. -/
theorem square_iff {d r : Nat} (hlo : r * r ≤ d) (hhi : d < (r + 1) * (r + 1)) :
    r * r = d ↔ ∃ n, d = n * n := by
  constructor
  · intro h; exact ⟨r, h.symm⟩
  · rintro ⟨n, rfl⟩
    have h1 : n < r + 1 := by nlinarith
    have h2 : r < n + 1 := by nlinarith
    have : n = r := by omega
    subst this; rfl

/-- If `s` is the integer square root of `4 * d + 1`, then `d` is pronic iff `s * s = 4 * d + 1`.
    `4 * n * (n + 1) + 1 = (2 * n + 1) ^ 2`, and an odd square has an odd root. -/
theorem pronic_iff {d s : Nat} (hlo : s * s ≤ 4 * d + 1) (hhi : 4 * d + 1 < (s + 1) * (s + 1)) :
    s * s = 4 * d + 1 ↔ ∃ n, d = n * (n + 1) := by
  rw [square_iff hlo hhi]
  constructor
  · rintro ⟨m, hm⟩
    have hodd : Odd (m * m) := by rw [← hm]; exact ⟨2 * d, by ring⟩
    obtain ⟨n, rfl⟩ := Nat.odd_mul.mp hodd |>.1
    exact ⟨n, by nlinarith⟩
  · rintro ⟨n, rfl⟩
    exact ⟨2 * n + 1, by ring⟩

theorem immediate_justification_window_val :
    config.IMMEDIATE_JUSTIFICATION_WINDOW.val = 5 := by
  simp [config.IMMEDIATE_JUSTIFICATION_WINDOW]

/-! ## `is_justifiable_after` -/

/-- `is_justifiable_after` returns `true` iff the slot is justifiable after the finalized slot.
    The `ok` result also shows that none of the multiplications or additions overflow. -/
theorem is_justifiable_after_spec (slot finalized_slot : U64) :
    lean_types.slot.is_justifiable_after slot finalized_slot
      ⦃ b => b = true ↔ IsJustifiableAfter slot.val finalized_slot.val ⦄ := by
  unfold lean_types.slot.is_justifiable_after
  step as ⟨o, o_post⟩
  rcases o with _ | delta
  · simp only at o_post
    simp only [spec_ok, IsJustifiableAfter, Bool.false_eq_true, false_iff]
    rintro ⟨h, -⟩; omega
  simp only at o_post ⊢
  obtain ⟨hle, hdelta, -⟩ := o_post
  have hw := immediate_justification_window_val
  split
  · simp only [spec_ok, IsJustifiableAfter, true_iff]
    exact ⟨hle, Or.inl (by scalar_tac)⟩
  have hbig : 5 < delta.val := by scalar_tac
  step as ⟨root, root_lo, root_hi⟩
  step as ⟨i, i_post⟩
  split
  · simp only [spec_ok, IsJustifiableAfter, true_iff]
    refine ⟨hle, Or.inr (Or.inl ?_)⟩
    rw [← hdelta]; exact (square_iff root_lo root_hi).mp (by scalar_tac)
  rename_i hne
  have hsq : ¬ ∃ n, delta.val = n * n := by
    rw [← square_iff root_lo root_hi]; intro h; apply hne; scalar_tac
  have hfrom := core.convert.num.FromU128U64.from_val_eq delta
  simp only [lift, bind_tc_ok]
  step as ⟨i2, i2_post⟩
  step as ⟨discriminant, discriminant_post⟩
  step as ⟨root1, root1_lo, root1_hi⟩
  step as ⟨i3, i3_post⟩
  have hdisc : discriminant.val = 4 * delta.val + 1 := by omega
  rw [hdisc] at root1_lo root1_hi
  have heq : i3 = discriminant ↔ root1.val * root1.val = 4 * delta.val + 1 := by
    constructor
    · intro h; subst h; omega
    · intro h; scalar_tac
  simp only [decide_eq_true_eq, IsJustifiableAfter, heq, pronic_iff root1_lo root1_hi, ← hdelta]
  constructor
  · intro h; exact ⟨hle, Or.inr (Or.inr h)⟩
  · rintro ⟨-, h5 | h | h⟩
    · omega
    · exact absurd h hsq
    · exact h

/-! ## `justified_index_after` -/

/-- `justified_index_after` returns `slot - finalized_slot - 1` when the slot is after the
    finalized slot and the index fits in a `usize`, and `none` otherwise. -/
theorem justified_index_after_spec (slot finalized_slot : U64) :
    lean_types.slot.justified_index_after slot finalized_slot
      ⦃ r => r.map (·.val) =
        if slot.val ≤ finalized_slot.val ∨ Usize.max < slot.val - finalized_slot.val - 1 then none
        else some (slot.val - finalized_slot.val - 1) ⦄ := by
  unfold lean_types.slot.justified_index_after
  step as ⟨o, o_post⟩
  rcases o with _ | delta
  · simp only at o_post ⊢
    simp only [spec_ok, Option.map_none]
    rw [if_pos (Or.inl (by omega))]
  simp only at o_post ⊢
  obtain ⟨hle, hdelta, -⟩ := o_post
  step as ⟨o1, o1_post⟩
  rcases o1 with _ | index
  · simp only at o1_post ⊢
    simp only [spec_ok, Option.map_none]
    rw [if_pos (Or.inl (by omega))]
  simp only at o1_post ⊢
  obtain ⟨hle1, hindex, -⟩ := o1_post
  have hmax : (UScalar.cast .U64 core.num.Usize.MAX).val = Usize.max := by
    rw [UScalar.cast_val_mod_pow_greater_numBits_eq]
    · simp
    · cases System.Platform.numBits_eq <;> simp [UScalarTy.numBits, *]
  step as ⟨i, i_post⟩
  have hi : i.val = Usize.max := by rw [i_post]; exact hmax
  split
  · simp only [spec_ok, Option.map_none]
    rw [if_pos (Or.inr (by scalar_tac))]
  have hfit : index.val ≤ Usize.max := by scalar_tac
  step with UScalar.cast_inBounds_spec as ⟨i1, i1_post⟩
  rw [if_neg (by omega), Option.map_some, Option.some.injEq]
  omega

/-- On a 64-bit target every index fits in a `usize`, so `justified_index_after` is exactly
    the leanSpec rule: `none` iff `slot ≤ finalized_slot`, else `slot - finalized_slot - 1`. -/
theorem justified_index_after_spec_64bit (slot finalized_slot : U64)
    (h64 : System.Platform.numBits = 64) :
    lean_types.slot.justified_index_after slot finalized_slot
      ⦃ r => r.map (·.val) = justifiedIndexAfter slot.val finalized_slot.val ⦄ := by
  apply spec_mono (justified_index_after_spec slot finalized_slot)
  intro r hr
  have hmax : Usize.max = U64.max := by simp [Usize.max, U64.max, Usize.numBits, U64.numBits, h64]
  rw [hr, justifiedIndexAfter]
  have : ¬ Usize.max < slot.val - finalized_slot.val - 1 := by scalar_tac
  simp only [this, or_false]

end LeanTypesProofs
