-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lean_types]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lean_types

/-- [core::num::{u64}::isqrt]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3654:8-3654:40
    Name pattern: [core::num::{u64}::isqrt]
    Visibility: public -/
@[rust_fun "core::num::{u64}::isqrt"]
axiom core.num.U64.isqrt : Std.U64 → Result Std.U64

/-- [core::num::{u128}::isqrt]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3654:8-3654:40
    Name pattern: [core::num::{u128}::isqrt]
    Visibility: public -/
@[rust_fun "core::num::{u128}::isqrt"]
axiom core.num.U128.isqrt : Std.U128 → Result Std.U128

/-- [lean_types::config::IMMEDIATE_JUSTIFICATION_WINDOW]
    Source: 'lean/lean_types/src/config.rs', lines 3:0-3:50
    Visibility: public -/
@[global_simps, irreducible]
def config.IMMEDIATE_JUSTIFICATION_WINDOW : Std.U64 := 5#u64

/-- [lean_types::slot::justified_index_after]:
    Source: 'lean/lean_types/src/slot.rs', lines 28:0-39:1 -/
def slot.justified_index_after
  (slot : Std.U64) (finalized_slot : Std.U64) : Result (Option Std.Usize) := do
  let o ← lift (U64.checked_sub slot finalized_slot)
  match o with
  | none => ok none
  | some delta =>
    let o1 ← lift (U64.checked_sub delta 1#u64)
    match o1 with
    | none => ok none
    | some index =>
      let i ← lift (UScalar.cast .U64 core.num.Usize.MAX)
      if index > i
      then ok none
      else let i1 ← lift (UScalar.cast .Usize index)
           ok (some i1)

/-- [lean_types::slot::is_justifiable_after]:
    Source: 'lean/lean_types/src/slot.rs', lines 41:0-58:1 -/
def slot.is_justifiable_after
  (slot : Std.U64) (finalized_slot : Std.U64) : Result Bool := do
  let o ← lift (U64.checked_sub slot finalized_slot)
  match o with
  | none => ok false
  | some delta =>
    if delta <= config.IMMEDIATE_JUSTIFICATION_WINDOW
    then ok true
    else
      let root ← core.num.U64.isqrt delta
      let i ← root * root
      if i = delta
      then ok true
      else
        let i1 ← lift (core.convert.num.FromU128U64.from delta)
        let i2 ← 4#u128 * i1
        let discriminant ← i2 + 1#u128
        let root1 ← core.num.U128.isqrt discriminant
        let i3 ← root1 * root1
        ok (i3 = discriminant)

end lean_types
