import EpochProofs.Equiv.BuilderPendingPayments
import EpochProofs.Equiv.EffectiveBalanceUpdates
import EpochProofs.Equiv.InactivityUpdates
import EpochProofs.Equiv.Slashings
import EpochProofs.Equiv.RewardsAndPenalties
import EpochProofs.Equiv.RegistryUpdates
import EpochProofs.Equiv.PendingDeposits
import EpochProofs.Equiv.PendingConsolidations
import EpochProofs.Sanity.RowsSinglePass
import EpochProofs.Sanity.LighthouseRowOrder
import EpochProofs.Equiv.SinglePassStep
import EpochProofs.Sanity.LighthouseSinglePass
import EpochProofs.Sanity.RowsEffectiveBalance
import EpochProofs.Sanity.Frame
import EpochProofs.Sanity.Effects
import EpochProofs.Sanity.Block.Withdrawals
import EpochProofs.Sanity.Block.ExecutionRequests
import EpochProofs.Sanity.Block.ParentPayload
import EpochProofs.Sanity.Block.Exits
import EpochProofs.Sanity.Block.Slashings
import EpochProofs.Sanity.Block.Attestations
import EpochProofs.Sanity.Block.SyncAggregate
import EpochProofs.Sanity.JustificationFinalization
import EpochProofs.Sanity.EpochCommittees
import EpochProofs.Sanity.Driver
import EpochProofs.Sanity.Invariants.ExitDelay
import EpochProofs.Sanity.Invariants.BalanceFloor
import EpochProofs.Sanity.Invariants.EpochEnd
import EpochProofs.Sanity.Invariants.Lengths
import EpochProofs.Sanity.Invariants.ExitEpochs
import EpochProofs.Sanity.Invariants.Reachable
import EpochProofs.Sanity.Invariants.LighthouseEpoch
import EpochProofs.Sanity.Invariants.Capstone
open EpochProofs.Spec
#print axioms EpochProofs.Spec.withdrawals_loop
#print axioms EpochProofs.Spec.process_builder_pending_payments_eq
#print axioms EpochProofs.Spec.process_builder_pending_payments_wellFormed
#print axioms EpochProofs.Spec.get_builder_payment_quorum_threshold_ok
#print axioms EpochProofs.loop0_spec
#print axioms EpochProofs.loop1_spec
#print axioms EpochProofs.loop2_spec
#print axioms EpochProofs.process_builder_pending_payments_spec
#print axioms EpochProofs.quorum_equiv
#print axioms EpochProofs.absPayment_default
#print axioms EpochProofs.builder_pending_payments_equiv
#print axioms EpochProofs.Spec.process_effective_balance_updates_eq
#print axioms EpochProofs.Spec.hysteresisThresholds_mainnet
#print axioms EpochProofs.Spec.newEffectiveBalance_le_max
#print axioms EpochProofs.Spec.newEffectiveBalance_in_band
#print axioms EpochProofs.hysteresis_thresholds_equiv
#print axioms EpochProofs.new_effective_balance_equiv
#print axioms EpochProofs.Spec.process_inactivity_updates_eq
#print axioms EpochProofs.Spec.inactivityScoreStep_leak_missed
#print axioms EpochProofs.Spec.inactivityScoreStep_participating_le
#print axioms EpochProofs.new_inactivity_score_equiv
#print axioms EpochProofs.Spec.process_slashings_eq
#print axioms EpochProofs.Spec.slashingBalanceStep_not_slashed
#print axioms EpochProofs.Spec.slashingBalanceStep_le
#print axioms EpochProofs.slashings_context_equiv
#print axioms EpochProofs.new_balance_after_slashing_equiv
#print axioms EpochProofs.Spec.rewardsSequential_eq_combined
#print axioms EpochProofs.Spec.rewards_saturation_example
#print axioms EpochProofs.Spec.rewardsCombined_eq_sequential
#print axioms EpochProofs.flag_delta_equiv
#print axioms EpochProofs.inactivity_penalty_equiv
#print axioms EpochProofs.new_balance_after_rewards_equiv
#print axioms EpochProofs.new_balance_after_rewards_eq_spec
#print axioms EpochProofs.Spec.registryStepIndependent_eq_exclusive
#print axioms EpochProofs.compute_activation_exit_epoch_equiv
#print axioms EpochProofs.exit_churn_limit_equiv
#print axioms EpochProofs.compute_exit_epoch_and_update_churn_equiv
#print axioms EpochProofs.eligibility_step_equiv
#print axioms EpochProofs.ejection_step_equiv
#print axioms EpochProofs.activation_step_equiv
#print axioms EpochProofs.registry_update_equiv
#print axioms EpochProofs.registry_update_eq_spec
#print axioms EpochProofs.Spec.depositLoop_append
#print axioms EpochProofs.Spec.exitChurnStep_ge
#print axioms EpochProofs.Spec.predictedStatus_eq_post_registry
#print axioms EpochProofs.deposit_status_eq
#print axioms EpochProofs.deposits_loop_spec
#print axioms EpochProofs.process_pending_deposits_equiv
#print axioms EpochProofs.Spec.forIn_eq_stepLoop
#print axioms EpochProofs.Spec.process_pending_consolidations_eq
#print axioms EpochProofs.consolidations_loop_spec
#print axioms EpochProofs.process_pending_consolidations_equiv
#print axioms EpochProofs.Spec.two_passes_eq_one_pass
#print axioms EpochProofs.Spec.process_inactivity_updates_rows
#print axioms EpochProofs.Spec.process_rewards_and_penalties_rows
#print axioms EpochProofs.Spec.process_registry_updates_rows
#print axioms EpochProofs.Spec.process_slashings_rows
#print axioms EpochProofs.Spec.process_effective_balance_updates_rows
#print axioms EpochProofs.Spec.separate_passes_eq_single_pass
#print axioms EpochProofs.Spec.lhRowStep_eq_singlePassStep
#print axioms EpochProofs.single_pass_step_equiv
#print axioms EpochProofs.Spec.rewardsCombined_eq_sequential_flags
#print axioms EpochProofs.Spec.rewardsBaseReward_bound
#print axioms EpochProofs.Spec.lhRowStep_eq_singlePassStep_of_bounds
#print axioms EpochProofs.Spec.process_effective_balance_updates_floor_mainnet
#print axioms EpochProofs.Spec.lighthouse_single_pass_eq_spec
#print axioms EpochProofs.Spec.process_slots_frame
#print axioms EpochProofs.Spec.process_slots_slot
#print axioms EpochProofs.Spec.process_withdrawals_ebStable
#print axioms EpochProofs.Spec.process_withdrawals_exitOrder
#print axioms EpochProofs.Spec.process_withdrawals_balances
#print axioms EpochProofs.Spec.process_deposit_request_effect
#print axioms EpochProofs.Spec.process_withdrawal_request_effect
#print axioms EpochProofs.Spec.process_consolidation_request_effect
#print axioms EpochProofs.Spec.process_parent_execution_payload_effect
#print axioms EpochProofs.Spec.process_parent_execution_payload_exitOrder
#print axioms EpochProofs.Spec.process_execution_payload_bid_frame
#print axioms EpochProofs.Spec.process_voluntary_exit_effects
#print axioms EpochProofs.Spec.process_bls_to_execution_change_effects
#print axioms EpochProofs.Spec.process_proposer_slashing_effects
#print axioms EpochProofs.Spec.process_attester_slashing_effects
#print axioms EpochProofs.Spec.process_attestation_ebStable
#print axioms EpochProofs.Spec.process_attestation_exitOrder
#print axioms EpochProofs.Spec.process_attestation_balancesUp
#print axioms EpochProofs.Spec.process_payload_attestation_eq
#print axioms EpochProofs.Spec.process_sync_aggregate_frame
#print axioms EpochProofs.Spec.process_sync_aggregate_balance_bound_mainnet
#print axioms EpochProofs.Spec.process_justification_and_finalization_ffg
#print axioms EpochProofs.Spec.process_slots_ffg
#print axioms EpochProofs.Spec.FfgInvariant.finalized_le
#print axioms EpochProofs.Spec.process_sync_committee_updates_frame
#print axioms EpochProofs.Spec.process_proposer_lookahead_frame
#print axioms EpochProofs.Spec.process_ptc_window_frame
#print axioms EpochProofs.Spec.process_epoch_ffg
#print axioms EpochProofs.Spec.process_slots_process_epoch_ffg
#print axioms EpochProofs.Spec.process_block_checkpointsStable
#print axioms EpochProofs.Spec.state_transition_ffg
#print axioms EpochProofs.Spec.process_epoch_exitDelay
#print axioms EpochProofs.Spec.process_block_budget_mainnet
#print axioms EpochProofs.Spec.boundary_effective_balance_mainnet
#print axioms EpochProofs.Spec.process_epoch_effective_balances
#print axioms EpochProofs.Spec.state_transition_rowsOk
#print axioms EpochProofs.Spec.reachable_inv
#print axioms EpochProofs.Spec.reachable_boundaryOk
#print axioms EpochProofs.Spec.reachable_state_transition_sameOk'
#print axioms EpochProofs.Spec.process_epoch_lh_sameOk'
#print axioms EpochProofs.Spec.lighthouse_state_transition_sameOk
