import EpochProofs.Equiv.BuilderPendingPayments
import EpochProofs.Equiv.EffectiveBalanceUpdates
import EpochProofs.Equiv.InactivityUpdates
import EpochProofs.Equiv.Slashings
import EpochProofs.Equiv.RewardsAndPenalties
open EpochProofs.Spec
#print axioms EpochProofs.Spec.withdrawals_loop
#print axioms EpochProofs.Spec.process_builder_pending_payments_eq
#print axioms EpochProofs.Spec.process_builder_pending_payments_wellFormed
#print axioms EpochProofs.Spec.get_builder_payment_quorum_threshold_ok
#print axioms EpochProofs.loop0_spec
#print axioms EpochProofs.loop1_spec
#print axioms EpochProofs.loop2_spec
#print axioms EpochProofs.process_builder_pending_payments_spec
#print axioms EpochProofs.quorum_equiv
#print axioms EpochProofs.absPayment_default
#print axioms EpochProofs.builder_pending_payments_equiv
#print axioms EpochProofs.Spec.process_effective_balance_updates_eq
#print axioms EpochProofs.Spec.hysteresisThresholds_mainnet
#print axioms EpochProofs.Spec.newEffectiveBalance_le_max
#print axioms EpochProofs.Spec.newEffectiveBalance_in_band
#print axioms EpochProofs.hysteresis_thresholds_equiv
#print axioms EpochProofs.new_effective_balance_equiv
#print axioms EpochProofs.Spec.process_inactivity_updates_eq
#print axioms EpochProofs.Spec.inactivityScoreStep_leak_missed
#print axioms EpochProofs.Spec.inactivityScoreStep_participating_le
#print axioms EpochProofs.new_inactivity_score_equiv
#print axioms EpochProofs.Spec.process_slashings_eq
#print axioms EpochProofs.Spec.slashingBalanceStep_not_slashed
#print axioms EpochProofs.Spec.slashingBalanceStep_le
#print axioms EpochProofs.slashings_context_equiv
#print axioms EpochProofs.new_balance_after_slashing_equiv
#print axioms EpochProofs.Spec.rewardsSequential_eq_combined
#print axioms EpochProofs.Spec.rewards_saturation_example
#print axioms EpochProofs.Spec.rewardsCombined_eq_sequential
#print axioms EpochProofs.flag_delta_equiv
#print axioms EpochProofs.inactivity_penalty_equiv
#print axioms EpochProofs.new_balance_after_rewards_equiv
#print axioms EpochProofs.new_balance_after_rewards_eq_spec
