-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [state_processing]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace state_processing

/-- [alloy_primitives::bits::fixed::FixedBytes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/fixed.rs', lines 36:0-36:37
    Name pattern: [alloy_primitives::bits::fixed::FixedBytes]
    Visibility: public -/
@[reducible, rust_type "alloy_primitives::bits::fixed::FixedBytes"]
def alloy_primitives.bits.fixed.FixedBytes (N : Std.Usize) := Array Std.U8 N

/-- [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<N>}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/fixed.rs', lines 386:4-386:24
    Name pattern: [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO"]
def alloy_primitives.bits.fixed.FixedBytes.ZERO (N : Std.Usize)
  : alloy_primitives.bits.fixed.FixedBytes N :=
  let a := Array.repeat N 0#u8
  a

/-- [alloy_primitives::bits::fixed::{impl core::default::Default for alloy_primitives::bits::fixed::FixedBytes<N>}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/fixed.rs', lines 42:4-42:24
    Name pattern: [alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default"]
def alloy_primitives.bits.fixed.FixedBytes.Insts.CoreDefaultDefault.default
  (N : Std.Usize) : Result (alloy_primitives.bits.fixed.FixedBytes N) := do
  ok (alloy_primitives.bits.fixed.FixedBytes.ZERO N)

/-- [alloy_primitives::bits::address::Address]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/macros.rs', lines 74:8-74:92
    Name pattern: [alloy_primitives::bits::address::Address]
    Visibility: public -/
@[reducible, rust_type "alloy_primitives::bits::address::Address"]
def alloy_primitives.bits.address.Address :=
  alloy_primitives.bits.fixed.FixedBytes 20#usize

/-- [alloy_primitives::bits::address::{impl core::clone::Clone for alloy_primitives::bits::address::Address}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/macros.rs', lines 42:12-42:17
    Name pattern: [alloy_primitives::bits::address::{core::clone::Clone<alloy_primitives::bits::address::Address>}::clone]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::address::{core::clone::Clone<alloy_primitives::bits::address::Address>}::clone"]
def alloy_primitives.bits.address.Address.Insts.CoreCloneClone.clone
  (self : alloy_primitives.bits.address.Address) :
  Result alloy_primitives.bits.address.Address
  := do
  ok self

/-- [alloy_primitives::bits::address::{impl core::default::Default for alloy_primitives::bits::address::Address}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/macros.rs', lines 44:12-44:19
    Name pattern: [alloy_primitives::bits::address::{core::default::Default<alloy_primitives::bits::address::Address>}::default]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::address::{core::default::Default<alloy_primitives::bits::address::Address>}::default"]
def alloy_primitives.bits.address.Address.Insts.CoreDefaultDefault.default
  : Result alloy_primitives.bits.address.Address := do
  let fb ←
    alloy_primitives.bits.fixed.FixedBytes.Insts.CoreDefaultDefault.default
      20#usize
  ok fb

/-- [safe_arith::ArithError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 75:0-75:19
    Name pattern: [safe_arith::ArithError]
    Visibility: public -/
@[discriminant isize, rust_type "safe_arith::ArithError"]
inductive safe_arith.ArithError where
| Overflow : safe_arith.ArithError
| DivisionByZero : safe_arith.ArithError

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_mul]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 150:12-150:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_mul]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_mul"]
def U64.Insts.Safe_arithSafeArithU64.safe_mul
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_mul self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_div]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 155:12-155:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_div]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_div"]
def U64.Insts.Safe_arithSafeArithU64.safe_div
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_div self other)
  core.option.Option.ok_or o safe_arith.ArithError.DivisionByZero

/-- [types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal]
    Source: 'consensus/types/src/builder/builder_pending_withdrawal.rs', lines 12:0-12:35
    Name pattern: [types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal]
    Visibility: public -/
@[rust_type
  "types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal"]
structure types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  where
  fee_recipient : alloy_primitives.bits.address.Address
  amount : Std.U64
  builder_index : Std.U64

/-- [types::builder::builder_pending_withdrawal::{impl core::clone::Clone for types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal}::clone]:
    Source: 'consensus/types/src/builder/builder_pending_withdrawal.rs', lines 8:32-8:37
    Name pattern: [types::builder::builder_pending_withdrawal::{core::clone::Clone<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::clone]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_withdrawal::{core::clone::Clone<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::clone"]
def
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreCloneClone.clone
  (self : types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal) :
  Result types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  := do
  let a ←
    alloy_primitives.bits.address.Address.Insts.CoreCloneClone.clone
      self.fee_recipient
  let i ← lift (core.clone.impls.CloneU64.clone self.amount)
  let i1 ← lift (core.clone.impls.CloneU64.clone self.builder_index)
  ok { fee_recipient := a, amount := i, builder_index := i1 }

/-- [types::builder::builder_pending_payment::BuilderPendingPayment]
    Source: 'consensus/types/src/builder/builder_pending_payment.rs', lines 12:0-12:32
    Name pattern: [types::builder::builder_pending_payment::BuilderPendingPayment]
    Visibility: public -/
@[rust_type "types::builder::builder_pending_payment::BuilderPendingPayment"]
structure types.builder.builder_pending_payment.BuilderPendingPayment where
  weight : Std.U64
  withdrawal :
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  proposer_index : Std.U64

/-- [types::builder::builder_pending_payment::{impl core::clone::Clone for types::builder::builder_pending_payment::BuilderPendingPayment}::clone]:
    Source: 'consensus/types/src/builder/builder_pending_payment.rs', lines 8:32-8:37
    Name pattern: [types::builder::builder_pending_payment::{core::clone::Clone<types::builder::builder_pending_payment::BuilderPendingPayment>}::clone]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_payment::{core::clone::Clone<types::builder::builder_pending_payment::BuilderPendingPayment>}::clone"]
def
  types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreCloneClone.clone
  (self : types.builder.builder_pending_payment.BuilderPendingPayment) :
  Result types.builder.builder_pending_payment.BuilderPendingPayment
  := do
  let i ← lift (core.clone.impls.CloneU64.clone self.weight)
  let bpw ←
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreCloneClone.clone
      self.withdrawal
  let i1 ← lift (core.clone.impls.CloneU64.clone self.proposer_index)
  ok { weight := i, withdrawal := bpw, proposer_index := i1 }

/-- [types::builder::builder_pending_withdrawal::{impl core::default::Default for types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal}::default]:
    Source: 'consensus/types/src/builder/builder_pending_withdrawal.rs', lines 8:39-8:46
    Name pattern: [types::builder::builder_pending_withdrawal::{core::default::Default<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::default]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_withdrawal::{core::default::Default<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::default"]
def
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreDefaultDefault.default
  :
  Result types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  := do
  let a ←
    alloy_primitives.bits.address.Address.Insts.CoreDefaultDefault.default
  ok
    {
      fee_recipient := a,
      amount := (core.default.DefaultU64.default),
      builder_index := (core.default.DefaultU64.default)
    }

/-- [types::builder::builder_pending_payment::{impl core::default::Default for types::builder::builder_pending_payment::BuilderPendingPayment}::default]:
    Source: 'consensus/types/src/builder/builder_pending_payment.rs', lines 8:39-8:46
    Name pattern: [types::builder::builder_pending_payment::{core::default::Default<types::builder::builder_pending_payment::BuilderPendingPayment>}::default]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_payment::{core::default::Default<types::builder::builder_pending_payment::BuilderPendingPayment>}::default"]
def
  types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreDefaultDefault.default
  : Result types.builder.builder_pending_payment.BuilderPendingPayment := do
  let bpw ←
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreDefaultDefault.default
  ok
    {
      weight := (core.default.DefaultU64.default),
      withdrawal := bpw,
      proposer_index := (core.default.DefaultU64.default)
    }

/-- [state_processing::per_epoch_processing::builder_pending_payments::get_builder_payment_quorum_threshold]:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 9:0-18:1
    Visibility: public -/
def
  per_epoch_processing.builder_pending_payments.get_builder_payment_quorum_threshold
  (total_active_balance : Std.U64) (slots_per_epoch : Std.U64)
  (numerator : Std.U64) (denominator : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_div total_active_balance
      slots_per_epoch
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← U64.Insts.Safe_arithSafeArithU64.safe_mul val numerator
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      U64.Insts.Safe_arithSafeArithU64.safe_div val1 denominator
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop body 0:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 28:4-35:5
    Visibility: public -/
@[rust_loop_body]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0.body
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (slots_per_epoch : Std.Usize) (quorum : Std.U64)
  (new_withdrawals : alloc.vec.Vec
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal) ×
    Std.Usize) (alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal))
  := do
  if i < slots_per_epoch
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        types.builder.builder_pending_payment.BuilderPendingPayment) payments i
    let new_withdrawals1 ←
      match o with
      | none => ok new_withdrawals
      | some payment =>
        if payment.weight >= quorum
        then
          do
          let bpw ←
            types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreCloneClone.clone
              payment.withdrawal
          alloc.vec.Vec.push new_withdrawals bpw
        else ok new_withdrawals
    let i1 ← lift (core.num.Usize.saturating_add i 1#usize)
    ok (cont (new_withdrawals1, i1))
  else ok (done new_withdrawals)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop 0:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 28:4-35:5
    Visibility: public -/
@[rust_loop]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (slots_per_epoch : Std.Usize) (quorum : Std.U64)
  (new_withdrawals : alloc.vec.Vec
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
  (i : Std.Usize) :
  Result (alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
  := do
  loop
    (fun (new_withdrawals1, i1) =>
      per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0.body
      payments slots_per_epoch quorum new_withdrawals1 i1)
    (new_withdrawals, i)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop body 1:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 39:4-44:5
    Visibility: public -/
@[rust_loop_body]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1.body
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment) × Std.Usize)
    (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment))
  := do
  let i1 := Slice.len payments
  if i < i1
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        types.builder.builder_pending_payment.BuilderPendingPayment) payments i
    let updated_payments1 ←
      match o with
      | none => ok updated_payments
      | some payment =>
        do
        let bpp ←
          types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreCloneClone.clone
            payment
        alloc.vec.Vec.push updated_payments bpp
    let i2 ← lift (core.num.Usize.saturating_add i 1#usize)
    ok (cont (updated_payments1, i2))
  else ok (done updated_payments)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop 1:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 39:4-44:5
    Visibility: public -/
@[rust_loop]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment)
  := do
  loop
    (fun (updated_payments1, i1) =>
      per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1.body
      payments updated_payments1 i1)
    (updated_payments, i)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop body 2:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 46:4-49:5
    Visibility: public -/
@[rust_loop_body]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2.body
  (slots_per_epoch : Std.Usize)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment) × Std.Usize)
    (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment))
  := do
  if i < slots_per_epoch
  then
    let bpp ←
      types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreDefaultDefault.default
    let updated_payments1 ← alloc.vec.Vec.push updated_payments bpp
    let i1 ← lift (core.num.Usize.saturating_add i 1#usize)
    ok (cont (updated_payments1, i1))
  else ok (done updated_payments)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop 2:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 46:4-49:5
    Visibility: public -/
@[rust_loop]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2
  (slots_per_epoch : Std.Usize)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment)
  := do
  loop
    (fun (updated_payments1, i1) =>
      per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2.body
      slots_per_epoch updated_payments1 i1)
    (updated_payments, i)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 21:0-52:1
    Visibility: public -/
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (slots_per_epoch : Std.Usize) (quorum : Std.U64) :
  Result ((alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal) ×
    (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment))
  := do
  let new_withdrawals ←
    per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0
      payments slots_per_epoch quorum (alloc.vec.Vec.new
      types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
      0#usize
  let updated_payments ←
    per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1
      payments (alloc.vec.Vec.new
      types.builder.builder_pending_payment.BuilderPendingPayment)
      slots_per_epoch
  let updated_payments1 ←
    per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2
      slots_per_epoch updated_payments 0#usize
  ok (new_withdrawals, updated_payments1)

end state_processing
