-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [state_processing]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace state_processing

/-- [alloy_primitives::bits::fixed::FixedBytes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/fixed.rs', lines 36:0-36:37
    Name pattern: [alloy_primitives::bits::fixed::FixedBytes]
    Visibility: public -/
@[reducible, rust_type "alloy_primitives::bits::fixed::FixedBytes"]
def alloy_primitives.bits.fixed.FixedBytes (N : Std.Usize) := Array Std.U8 N

/-- [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<N>}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/fixed.rs', lines 386:4-386:24
    Name pattern: [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO"]
def alloy_primitives.bits.fixed.FixedBytes.ZERO (N : Std.Usize)
  : alloy_primitives.bits.fixed.FixedBytes N :=
  let a := Array.repeat N 0#u8
  a

/-- [alloy_primitives::bits::fixed::{impl core::default::Default for alloy_primitives::bits::fixed::FixedBytes<N>}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/fixed.rs', lines 42:4-42:24
    Name pattern: [alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default"]
def alloy_primitives.bits.fixed.FixedBytes.Insts.CoreDefaultDefault.default
  (N : Std.Usize) : Result (alloy_primitives.bits.fixed.FixedBytes N) := do
  ok (alloy_primitives.bits.fixed.FixedBytes.ZERO N)

/-- [alloy_primitives::bits::address::Address]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/macros.rs', lines 74:8-74:92
    Name pattern: [alloy_primitives::bits::address::Address]
    Visibility: public -/
@[reducible, rust_type "alloy_primitives::bits::address::Address"]
def alloy_primitives.bits.address.Address :=
  alloy_primitives.bits.fixed.FixedBytes 20#usize

/-- [alloy_primitives::bits::address::{impl core::clone::Clone for alloy_primitives::bits::address::Address}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/macros.rs', lines 42:12-42:17
    Name pattern: [alloy_primitives::bits::address::{core::clone::Clone<alloy_primitives::bits::address::Address>}::clone]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::address::{core::clone::Clone<alloy_primitives::bits::address::Address>}::clone"]
def alloy_primitives.bits.address.Address.Insts.CoreCloneClone.clone
  (self : alloy_primitives.bits.address.Address) :
  Result alloy_primitives.bits.address.Address
  := do
  ok self

/-- [alloy_primitives::bits::address::{impl core::default::Default for alloy_primitives::bits::address::Address}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.5.0/src/bits/macros.rs', lines 44:12-44:19
    Name pattern: [alloy_primitives::bits::address::{core::default::Default<alloy_primitives::bits::address::Address>}::default]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::address::{core::default::Default<alloy_primitives::bits::address::Address>}::default"]
def alloy_primitives.bits.address.Address.Insts.CoreDefaultDefault.default
  : Result alloy_primitives.bits.address.Address := do
  let fb ←
    alloy_primitives.bits.fixed.FixedBytes.Insts.CoreDefaultDefault.default
      20#usize
  ok fb

/-- [safe_arith::ArithError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 75:0-75:19
    Name pattern: [safe_arith::ArithError]
    Visibility: public -/
@[discriminant isize, rust_type "safe_arith::ArithError"]
inductive safe_arith.ArithError where
| Overflow : safe_arith.ArithError
| DivisionByZero : safe_arith.ArithError

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 140:12-140:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_add]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_add"]
def U64.Insts.Safe_arithSafeArithU64.safe_add
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_add self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 145:12-145:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_sub]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_sub"]
def U64.Insts.Safe_arithSafeArithU64.safe_sub
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_sub self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_mul]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 150:12-150:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_mul]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_mul"]
def U64.Insts.Safe_arithSafeArithU64.safe_mul
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_mul self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_div]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 155:12-155:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_div]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_div"]
def U64.Insts.Safe_arithSafeArithU64.safe_div
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_div self other)
  core.option.Option.ok_or o safe_arith.ArithError.DivisionByZero

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_rem]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 160:12-160:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_rem]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_rem"]
def U64.Insts.Safe_arithSafeArithU64.safe_rem
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_rem self other)
  core.option.Option.ok_or o safe_arith.ArithError.DivisionByZero

/-- [types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal]
    Source: 'consensus/types/src/builder/builder_pending_withdrawal.rs', lines 12:0-12:35
    Name pattern: [types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal]
    Visibility: public -/
@[rust_type
  "types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal"]
structure types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  where
  fee_recipient : alloy_primitives.bits.address.Address
  amount : Std.U64
  builder_index : Std.U64

/-- [types::builder::builder_pending_withdrawal::{impl core::clone::Clone for types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal}::clone]:
    Source: 'consensus/types/src/builder/builder_pending_withdrawal.rs', lines 8:32-8:37
    Name pattern: [types::builder::builder_pending_withdrawal::{core::clone::Clone<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::clone]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_withdrawal::{core::clone::Clone<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::clone"]
def
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreCloneClone.clone
  (self : types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal) :
  Result types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  := do
  let a ←
    alloy_primitives.bits.address.Address.Insts.CoreCloneClone.clone
      self.fee_recipient
  let i ← lift (core.clone.impls.CloneU64.clone self.amount)
  let i1 ← lift (core.clone.impls.CloneU64.clone self.builder_index)
  ok { fee_recipient := a, amount := i, builder_index := i1 }

/-- [types::builder::builder_pending_payment::BuilderPendingPayment]
    Source: 'consensus/types/src/builder/builder_pending_payment.rs', lines 12:0-12:32
    Name pattern: [types::builder::builder_pending_payment::BuilderPendingPayment]
    Visibility: public -/
@[rust_type "types::builder::builder_pending_payment::BuilderPendingPayment"]
structure types.builder.builder_pending_payment.BuilderPendingPayment where
  weight : Std.U64
  withdrawal :
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  proposer_index : Std.U64

/-- [types::builder::builder_pending_payment::{impl core::clone::Clone for types::builder::builder_pending_payment::BuilderPendingPayment}::clone]:
    Source: 'consensus/types/src/builder/builder_pending_payment.rs', lines 8:32-8:37
    Name pattern: [types::builder::builder_pending_payment::{core::clone::Clone<types::builder::builder_pending_payment::BuilderPendingPayment>}::clone]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_payment::{core::clone::Clone<types::builder::builder_pending_payment::BuilderPendingPayment>}::clone"]
def
  types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreCloneClone.clone
  (self : types.builder.builder_pending_payment.BuilderPendingPayment) :
  Result types.builder.builder_pending_payment.BuilderPendingPayment
  := do
  let i ← lift (core.clone.impls.CloneU64.clone self.weight)
  let bpw ←
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreCloneClone.clone
      self.withdrawal
  let i1 ← lift (core.clone.impls.CloneU64.clone self.proposer_index)
  ok { weight := i, withdrawal := bpw, proposer_index := i1 }

/-- [types::builder::builder_pending_withdrawal::{impl core::default::Default for types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal}::default]:
    Source: 'consensus/types/src/builder/builder_pending_withdrawal.rs', lines 8:39-8:46
    Name pattern: [types::builder::builder_pending_withdrawal::{core::default::Default<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::default]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_withdrawal::{core::default::Default<types::builder::builder_pending_withdrawal::BuilderPendingWithdrawal>}::default"]
def
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreDefaultDefault.default
  :
  Result types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal
  := do
  let a ←
    alloy_primitives.bits.address.Address.Insts.CoreDefaultDefault.default
  ok
    {
      fee_recipient := a,
      amount := (core.default.DefaultU64.default),
      builder_index := (core.default.DefaultU64.default)
    }

/-- [types::builder::builder_pending_payment::{impl core::default::Default for types::builder::builder_pending_payment::BuilderPendingPayment}::default]:
    Source: 'consensus/types/src/builder/builder_pending_payment.rs', lines 8:39-8:46
    Name pattern: [types::builder::builder_pending_payment::{core::default::Default<types::builder::builder_pending_payment::BuilderPendingPayment>}::default]
    Visibility: public -/
@[rust_fun
  "types::builder::builder_pending_payment::{core::default::Default<types::builder::builder_pending_payment::BuilderPendingPayment>}::default"]
def
  types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreDefaultDefault.default
  : Result types.builder.builder_pending_payment.BuilderPendingPayment := do
  let bpw ←
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreDefaultDefault.default
  ok
    {
      weight := (core.default.DefaultU64.default),
      withdrawal := bpw,
      proposer_index := (core.default.DefaultU64.default)
    }

/-- [types::core::consts::altair::TIMELY_SOURCE_WEIGHT]
    Source: 'consensus/types/src/core/consts.rs', lines 5:4-5:39
    Name pattern: [types::core::consts::altair::TIMELY_SOURCE_WEIGHT]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "types::core::consts::altair::TIMELY_SOURCE_WEIGHT"]
def types.core.consts.altair.TIMELY_SOURCE_WEIGHT : Std.U64 := 14#u64

/-- [types::core::consts::altair::TIMELY_TARGET_WEIGHT]
    Source: 'consensus/types/src/core/consts.rs', lines 6:4-6:39
    Name pattern: [types::core::consts::altair::TIMELY_TARGET_WEIGHT]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "types::core::consts::altair::TIMELY_TARGET_WEIGHT"]
def types.core.consts.altair.TIMELY_TARGET_WEIGHT : Std.U64 := 26#u64

/-- [types::core::consts::altair::TIMELY_HEAD_WEIGHT]
    Source: 'consensus/types/src/core/consts.rs', lines 7:4-7:37
    Name pattern: [types::core::consts::altair::TIMELY_HEAD_WEIGHT]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "types::core::consts::altair::TIMELY_HEAD_WEIGHT"]
def types.core.consts.altair.TIMELY_HEAD_WEIGHT : Std.U64 := 14#u64

/-- [types::core::consts::altair::WEIGHT_DENOMINATOR]
    Source: 'consensus/types/src/core/consts.rs', lines 10:4-10:37
    Name pattern: [types::core::consts::altair::WEIGHT_DENOMINATOR]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "types::core::consts::altair::WEIGHT_DENOMINATOR"]
def types.core.consts.altair.WEIGHT_DENOMINATOR : Std.U64 := 64#u64

/-- [state_processing::per_epoch_processing::builder_pending_payments::get_builder_payment_quorum_threshold]:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 9:0-18:1
    Visibility: public -/
def
  per_epoch_processing.builder_pending_payments.get_builder_payment_quorum_threshold
  (total_active_balance : Std.U64) (slots_per_epoch : Std.U64)
  (numerator : Std.U64) (denominator : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_div total_active_balance
      slots_per_epoch
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← U64.Insts.Safe_arithSafeArithU64.safe_mul val numerator
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      U64.Insts.Safe_arithSafeArithU64.safe_div val1 denominator
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop body 0:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 28:4-35:5
    Visibility: public -/
@[rust_loop_body]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0.body
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (slots_per_epoch : Std.Usize) (quorum : Std.U64)
  (new_withdrawals : alloc.vec.Vec
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal) ×
    Std.Usize) (alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal))
  := do
  if i < slots_per_epoch
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        types.builder.builder_pending_payment.BuilderPendingPayment) payments i
    let new_withdrawals1 ←
      match o with
      | none => ok new_withdrawals
      | some payment =>
        if payment.weight >= quorum
        then
          do
          let bpw ←
            types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal.Insts.CoreCloneClone.clone
              payment.withdrawal
          alloc.vec.Vec.push new_withdrawals bpw
        else ok new_withdrawals
    let i1 ← lift (core.num.Usize.saturating_add i 1#usize)
    ok (cont (new_withdrawals1, i1))
  else ok (done new_withdrawals)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop 0:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 28:4-35:5
    Visibility: public -/
@[rust_loop]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (slots_per_epoch : Std.Usize) (quorum : Std.U64)
  (new_withdrawals : alloc.vec.Vec
  types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
  (i : Std.Usize) :
  Result (alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
  := do
  loop
    (fun (new_withdrawals1, i1) =>
      per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0.body
      payments slots_per_epoch quorum new_withdrawals1 i1)
    (new_withdrawals, i)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop body 1:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 39:4-44:5
    Visibility: public -/
@[rust_loop_body]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1.body
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment) × Std.Usize)
    (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment))
  := do
  let i1 := Slice.len payments
  if i < i1
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        types.builder.builder_pending_payment.BuilderPendingPayment) payments i
    let updated_payments1 ←
      match o with
      | none => ok updated_payments
      | some payment =>
        do
        let bpp ←
          types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreCloneClone.clone
            payment
        alloc.vec.Vec.push updated_payments bpp
    let i2 ← lift (core.num.Usize.saturating_add i 1#usize)
    ok (cont (updated_payments1, i2))
  else ok (done updated_payments)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop 1:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 39:4-44:5
    Visibility: public -/
@[rust_loop]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment)
  := do
  loop
    (fun (updated_payments1, i1) =>
      per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1.body
      payments updated_payments1 i1)
    (updated_payments, i)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop body 2:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 46:4-49:5
    Visibility: public -/
@[rust_loop_body]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2.body
  (slots_per_epoch : Std.Usize)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment) × Std.Usize)
    (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment))
  := do
  if i < slots_per_epoch
  then
    let bpp ←
      types.builder.builder_pending_payment.BuilderPendingPayment.Insts.CoreDefaultDefault.default
    let updated_payments1 ← alloc.vec.Vec.push updated_payments bpp
    let i1 ← lift (core.num.Usize.saturating_add i 1#usize)
    ok (cont (updated_payments1, i1))
  else ok (done updated_payments)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]: loop 2:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 46:4-49:5
    Visibility: public -/
@[rust_loop]
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2
  (slots_per_epoch : Std.Usize)
  (updated_payments : alloc.vec.Vec
  types.builder.builder_pending_payment.BuilderPendingPayment) (i : Std.Usize)
  :
  Result (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment)
  := do
  loop
    (fun (updated_payments1, i1) =>
      per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2.body
      slots_per_epoch updated_payments1 i1)
    (updated_payments, i)

/-- [state_processing::per_epoch_processing::builder_pending_payments::process_builder_pending_payments]:
    Source: 'consensus/state_processing/src/per_epoch_processing/builder_pending_payments.rs', lines 21:0-52:1
    Visibility: public -/
def
  per_epoch_processing.builder_pending_payments.process_builder_pending_payments
  (payments : Slice
  types.builder.builder_pending_payment.BuilderPendingPayment)
  (slots_per_epoch : Std.Usize) (quorum : Std.U64) :
  Result ((alloc.vec.Vec
    types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal) ×
    (alloc.vec.Vec
    types.builder.builder_pending_payment.BuilderPendingPayment))
  := do
  let new_withdrawals ←
    per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop0
      payments slots_per_epoch quorum (alloc.vec.Vec.new
      types.builder.builder_pending_withdrawal.BuilderPendingWithdrawal)
      0#usize
  let updated_payments ←
    per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop1
      payments (alloc.vec.Vec.new
      types.builder.builder_pending_payment.BuilderPendingPayment)
      slots_per_epoch
  let updated_payments1 ←
    per_epoch_processing.builder_pending_payments.process_builder_pending_payments_loop2
      slots_per_epoch updated_payments 0#usize
  ok (new_withdrawals, updated_payments1)

/-- [state_processing::per_epoch_processing::effective_balance::hysteresis_thresholds]:
    Source: 'consensus/state_processing/src/per_epoch_processing/effective_balance.rs', lines 10:0-20:1
    Visibility: public -/
def per_epoch_processing.effective_balance.hysteresis_thresholds
  (effective_balance_increment : Std.U64) (hysteresis_quotient : Std.U64)
  (hysteresis_downward_multiplier : Std.U64)
  (hysteresis_upward_multiplier : Std.U64) :
  Result (core.result.Result (Std.U64 × Std.U64) safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_div effective_balance_increment
      hysteresis_quotient
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ←
      U64.Insts.Safe_arithSafeArithU64.safe_mul val
        hysteresis_downward_multiplier
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r2 ←
        U64.Insts.Safe_arithSafeArithU64.safe_mul val
          hysteresis_upward_multiplier
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        ok (core.result.Result.Ok (val1, val2))
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
          residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
        residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
      residual

/-- [state_processing::per_epoch_processing::effective_balance::new_effective_balance]:
    Source: 'consensus/state_processing/src/per_epoch_processing/effective_balance.rs', lines 23:0-41:1
    Visibility: public -/
def per_epoch_processing.effective_balance.new_effective_balance
  (balance : Std.U64) (effective_balance : Std.U64)
  (effective_balance_limit : Std.U64) (downward_threshold : Std.U64)
  (upward_threshold : Std.U64) (effective_balance_increment : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_add balance downward_threshold
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val < effective_balance
    then
      let r1 ←
        U64.Insts.Safe_arithSafeArithU64.safe_rem balance
          effective_balance_increment
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let r2 ← U64.Insts.Safe_arithSafeArithU64.safe_sub balance val1
        let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let i ← core.cmp.min core.cmp.OrdU64 val2 effective_balance_limit
          ok (core.result.Result.Ok i)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
    else
      let r1 ←
        U64.Insts.Safe_arithSafeArithU64.safe_add effective_balance
          upward_threshold
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        if val1 < balance
        then
          let r2 ←
            U64.Insts.Safe_arithSafeArithU64.safe_rem balance
              effective_balance_increment
          let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue val2 =>
            let r3 ← U64.Insts.Safe_arithSafeArithU64.safe_sub balance val2
            let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
            match cf3 with
            | core.ops.control_flow.ControlFlow.Continue val3 =>
              let i ←
                core.cmp.min core.cmp.OrdU64 val3 effective_balance_limit
              ok (core.result.Result.Ok i)
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
        else ok (core.result.Result.Ok effective_balance)
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::inactivity_updates::new_inactivity_score]:
    Source: 'consensus/state_processing/src/per_epoch_processing/inactivity_updates.rs', lines 9:0-37:1
    Visibility: public -/
def per_epoch_processing.inactivity_updates.new_inactivity_score
  (inactivity_score : Std.U64) (is_eligible : Bool)
  (is_unslashed_participating_target : Bool) (is_in_inactivity_leak : Bool)
  (inactivity_score_bias : Std.U64) (inactivity_score_recovery_rate : Std.U64)
  :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  if is_eligible
  then
    if is_unslashed_participating_target
    then
      if inactivity_score = 0#u64
      then ok (core.result.Result.Ok 0#u64)
      else
        let r ←
          U64.Insts.Safe_arithSafeArithU64.safe_sub inactivity_score 1#u64
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          if is_in_inactivity_leak
          then ok (core.result.Result.Ok val)
          else
            let deduction ←
              core.cmp.min core.cmp.OrdU64 inactivity_score_recovery_rate val
            let r1 ← U64.Insts.Safe_arithSafeArithU64.safe_sub val deduction
            let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
            match cf1 with
            | core.ops.control_flow.ControlFlow.Continue val1 =>
              ok (core.result.Result.Ok val1)
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
    else
      let r ←
        U64.Insts.Safe_arithSafeArithU64.safe_add inactivity_score
          inactivity_score_bias
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        if is_in_inactivity_leak
        then ok (core.result.Result.Ok val)
        else
          let deduction ←
            core.cmp.min core.cmp.OrdU64 inactivity_score_recovery_rate val
          let r1 ← U64.Insts.Safe_arithSafeArithU64.safe_sub val deduction
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            ok (core.result.Result.Ok val1)
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  else ok (core.result.Result.Ok inactivity_score)

/-- [state_processing::per_epoch_processing::pending_deposits::DepositView]
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 9:0-19:1
    Visibility: public -/
structure per_epoch_processing.pending_deposits.DepositView where
  slot : Std.U64
  amount : Std.U64
  is_known_validator : Bool
  exit_epoch : Std.U64
  withdrawable_epoch : Std.U64
  activation_epoch : Std.U64
  effective_balance : Std.U64
  eth1_bridge_blocked : Bool

/-- [state_processing::per_epoch_processing::pending_deposits::DepositConstants]
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 22:0-29:1
    Visibility: public -/
structure per_epoch_processing.pending_deposits.DepositConstants where
  far_future_epoch : Std.U64
  ejection_balance : Std.U64
  max_pending_deposits_per_epoch : Std.U64
  registry_updates : Bool

/-- [state_processing::per_epoch_processing::pending_deposits::DepositsOutcome]
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 32:0-37:1
    Visibility: public -/
structure per_epoch_processing.pending_deposits.DepositsOutcome where
  next_deposit_index : Std.U64
  deposit_balance_to_consume : Std.U64
  postponed : alloc.vec.Vec Bool

/-- [state_processing::per_epoch_processing::pending_deposits::deposit_status]:
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 41:0-59:1
    Visibility: public -/
def per_epoch_processing.pending_deposits.deposit_status
  (view : per_epoch_processing.pending_deposits.DepositView)
  (current_epoch : Std.U64) (next_epoch : Std.U64)
  (constants : per_epoch_processing.pending_deposits.DepositConstants) :
  Result (Bool × Bool)
  := do
  if view.is_known_validator
  then
    let is_active ←
      if view.activation_epoch <= current_epoch
      then ok (current_epoch < view.exit_epoch)
      else ok false
    let will_be_exited ←
      if constants.registry_updates
      then
        if is_active
        then ok (view.effective_balance <= constants.ejection_balance)
        else ok false
      else ok false
    let b ←
      if view.exit_epoch < constants.far_future_epoch
      then ok true
      else ok will_be_exited
    ok (b, view.withdrawable_epoch < next_epoch)
  else ok (false, false)

/-- [state_processing::per_epoch_processing::pending_deposits::process_pending_deposits]: loop body 0:
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 78:4-111:5
    Visibility: public -/
@[rust_loop_body]
def per_epoch_processing.pending_deposits.process_pending_deposits_loop.body
  (views : Slice per_epoch_processing.pending_deposits.DepositView)
  (finalized_slot : Std.U64) (current_epoch : Std.U64) (next_epoch : Std.U64)
  (constants : per_epoch_processing.pending_deposits.DepositConstants)
  (available_for_processing : Std.U64) (processed_amount : Std.U64)
  (next_deposit_index : Std.U64) (postponed : alloc.vec.Vec Bool)
  (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.U64 × (alloc.vec.Vec Bool) × Std.Usize)
    (Std.U64 × Std.U64 × Bool × Bool × (alloc.vec.Vec Bool)))
  := do
  let i1 := Slice.len views
  if i < i1
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        per_epoch_processing.pending_deposits.DepositView) views i
    match o with
    | none =>
      let i2 ← lift (core.num.Usize.saturating_add i 1#usize)
      ok (cont (processed_amount, next_deposit_index, postponed, i2))
    | some view =>
      if view.eth1_bridge_blocked
      then
        ok (done (processed_amount, next_deposit_index, false, false,
          postponed))
      else
        if view.slot > finalized_slot
        then
          ok (done (processed_amount, next_deposit_index, false, false,
            postponed))
        else
          if next_deposit_index >= constants.max_pending_deposits_per_epoch
          then
            ok (done (processed_amount, next_deposit_index, false, false,
              postponed))
          else
            let (is_exited, is_withdrawn) ←
              per_epoch_processing.pending_deposits.deposit_status view
                current_epoch next_epoch constants
            if is_withdrawn
            then
              let postponed1 ← alloc.vec.Vec.push postponed false
              let next_deposit_index1 ←
                lift (core.num.U64.saturating_add next_deposit_index 1#u64)
              let i2 ← lift (core.num.Usize.saturating_add i 1#usize)
              ok (cont (processed_amount, next_deposit_index1, postponed1, i2))
            else
              if is_exited
              then
                let postponed1 ← alloc.vec.Vec.push postponed true
                let next_deposit_index1 ←
                  lift (core.num.U64.saturating_add next_deposit_index 1#u64)
                let i2 ← lift (core.num.Usize.saturating_add i 1#usize)
                ok (cont (processed_amount, next_deposit_index1, postponed1,
                  i2))
              else
                let o1 ← lift (U64.checked_add processed_amount view.amount)
                match o1 with
                | none =>
                  ok (done (processed_amount, next_deposit_index, false, true,
                    postponed))
                | some total =>
                  if total > available_for_processing
                  then
                    ok (done (processed_amount, next_deposit_index, true,
                      false, postponed))
                  else
                    let postponed1 ← alloc.vec.Vec.push postponed false
                    let next_deposit_index1 ←
                      lift (core.num.U64.saturating_add next_deposit_index
                        1#u64)
                    let i2 ← lift (core.num.Usize.saturating_add i 1#usize)
                    ok (cont (total, next_deposit_index1, postponed1, i2))
  else
    ok (done (processed_amount, next_deposit_index, false, false, postponed))

/-- [state_processing::per_epoch_processing::pending_deposits::process_pending_deposits]: loop 0:
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 78:4-111:5
    Visibility: public -/
@[rust_loop]
def per_epoch_processing.pending_deposits.process_pending_deposits_loop
  (views : Slice per_epoch_processing.pending_deposits.DepositView)
  (finalized_slot : Std.U64) (current_epoch : Std.U64) (next_epoch : Std.U64)
  (constants : per_epoch_processing.pending_deposits.DepositConstants)
  (available_for_processing : Std.U64) (processed_amount : Std.U64)
  (next_deposit_index : Std.U64) (postponed : alloc.vec.Vec Bool)
  (i : Std.Usize) :
  Result (Std.U64 × Std.U64 × Bool × Bool × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (processed_amount1, next_deposit_index1, postponed1, i1) =>
      per_epoch_processing.pending_deposits.process_pending_deposits_loop.body
      views finalized_slot current_epoch next_epoch constants
      available_for_processing processed_amount1 next_deposit_index1 postponed1
      i1)
    (processed_amount, next_deposit_index, postponed, i)

/-- [state_processing::per_epoch_processing::pending_deposits::process_pending_deposits]:
    Source: 'consensus/state_processing/src/per_epoch_processing/pending_deposits.rs', lines 62:0-126:1
    Visibility: public -/
def per_epoch_processing.pending_deposits.process_pending_deposits
  (views : Slice per_epoch_processing.pending_deposits.DepositView)
  (finalized_slot : Std.U64) (current_epoch : Std.U64) (next_epoch : Std.U64)
  (deposit_balance_to_consume : Std.U64) (activation_churn_limit : Std.U64)
  (constants : per_epoch_processing.pending_deposits.DepositConstants) :
  Result (core.result.Result
    per_epoch_processing.pending_deposits.DepositsOutcome
    safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_add deposit_balance_to_consume
      activation_churn_limit
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (processed_amount, next_deposit_index, is_churn_limit_reached,
      overflow, postponed) ←
      per_epoch_processing.pending_deposits.process_pending_deposits_loop views
        finalized_slot current_epoch next_epoch constants val 0#u64 0#u64
        (alloc.vec.Vec.new Bool) 0#usize
    if overflow
    then ok (core.result.Result.Err safe_arith.ArithError.Overflow)
    else
      if is_churn_limit_reached
      then
        let r1 ←
          U64.Insts.Safe_arithSafeArithU64.safe_sub val processed_amount
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          ok (core.result.Result.Ok
            { next_deposit_index, deposit_balance_to_consume := val1, postponed
            })
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            per_epoch_processing.pending_deposits.DepositsOutcome
            (core.convert.FromSame safe_arith.ArithError) residual
      else
        ok (core.result.Result.Ok
          { next_deposit_index, deposit_balance_to_consume := 0#u64, postponed
          })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      per_epoch_processing.pending_deposits.DepositsOutcome
      (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::registry_update::RegistryFields]
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 9:0-16:1
    Visibility: public -/
structure per_epoch_processing.registry_update.RegistryFields where
  activation_eligibility_epoch : Std.U64
  activation_epoch : Std.U64
  exit_epoch : Std.U64
  withdrawable_epoch : Std.U64
  earliest_exit_epoch : Std.U64
  exit_balance_to_consume : Std.U64

/-- [state_processing::per_epoch_processing::registry_update::RegistryConstants]
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 19:0-30:1
    Visibility: public -/
structure per_epoch_processing.registry_update.RegistryConstants where
  far_future_epoch : Std.U64
  min_activation_balance : Std.U64
  ejection_balance : Std.U64
  max_seed_lookahead : Std.U64
  min_validator_withdrawability_delay : Std.U64
  min_per_epoch_churn_limit : Std.U64
  churn_limit_quotient : Std.U64
  effective_balance_increment : Std.U64
  exit_churn_cap : Std.U64

/-- [state_processing::per_epoch_processing::registry_update::compute_activation_exit_epoch]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 32:0-37:1
    Visibility: public -/
def per_epoch_processing.registry_update.compute_activation_exit_epoch
  (epoch : Std.U64) (max_seed_lookahead : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let r ← U64.Insts.Safe_arithSafeArithU64.safe_add epoch 1#u64
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    U64.Insts.Safe_arithSafeArithU64.safe_add val max_seed_lookahead
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::registry_update::exit_churn_limit]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 40:0-50:1
    Visibility: public -/
def per_epoch_processing.registry_update.exit_churn_limit
  (total_active_balance : Std.U64)
  (constants : per_epoch_processing.registry_update.RegistryConstants) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_div total_active_balance
      constants.churn_limit_quotient
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let churn ←
      core.cmp.max core.cmp.OrdU64 constants.min_per_epoch_churn_limit val
    let r1 ←
      U64.Insts.Safe_arithSafeArithU64.safe_rem churn
        constants.effective_balance_increment
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r2 ← U64.Insts.Safe_arithSafeArithU64.safe_sub churn val1
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let i ← core.cmp.min core.cmp.OrdU64 constants.exit_churn_cap val2
        ok (core.result.Result.Ok i)
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::registry_update::compute_exit_epoch_and_update_churn]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 53:0-89:1
    Visibility: public -/
def per_epoch_processing.registry_update.compute_exit_epoch_and_update_churn
  (exit_balance : Std.U64) (current_epoch : Std.U64)
  (earliest_exit_epoch_state : Std.U64)
  (exit_balance_to_consume_state : Std.U64) (total_active_balance : Std.U64)
  (constants : per_epoch_processing.registry_update.RegistryConstants) :
  Result (core.result.Result (Std.U64 × Std.U64 × Std.U64)
    safe_arith.ArithError)
  := do
  let r ←
    per_epoch_processing.registry_update.compute_activation_exit_epoch
      current_epoch constants.max_seed_lookahead
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let earliest_exit_epoch ←
      core.cmp.max core.cmp.OrdU64 earliest_exit_epoch_state val
    let r1 ←
      per_epoch_processing.registry_update.exit_churn_limit
        total_active_balance constants
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let exit_balance_to_consume ←
        if earliest_exit_epoch_state < earliest_exit_epoch
        then ok val1
        else ok exit_balance_to_consume_state
      if exit_balance > exit_balance_to_consume
      then
        let r2 ←
          U64.Insts.Safe_arithSafeArithU64.safe_sub exit_balance
            exit_balance_to_consume
        let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let r3 ← U64.Insts.Safe_arithSafeArithU64.safe_sub val2 1#u64
          let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue val3 =>
            let r4 ← U64.Insts.Safe_arithSafeArithU64.safe_div val3 val1
            let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue val4 =>
              let r5 ← U64.Insts.Safe_arithSafeArithU64.safe_add val4 1#u64
              let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
              match cf5 with
              | core.ops.control_flow.ControlFlow.Continue val5 =>
                let r6 ←
                  U64.Insts.Safe_arithSafeArithU64.safe_add earliest_exit_epoch
                    val5
                let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                match cf6 with
                | core.ops.control_flow.ControlFlow.Continue val6 =>
                  let r7 ←
                    U64.Insts.Safe_arithSafeArithU64.safe_mul val5 val1
                  let cf7 ← core.result.Result.Insts.CoreOpsTry.branch r7
                  match cf7 with
                  | core.ops.control_flow.ControlFlow.Continue val7 =>
                    let r8 ←
                      U64.Insts.Safe_arithSafeArithU64.safe_add
                        exit_balance_to_consume val7
                    let cf8 ← core.result.Result.Insts.CoreOpsTry.branch r8
                    match cf8 with
                    | core.ops.control_flow.ControlFlow.Continue val8 =>
                      let r9 ←
                        U64.Insts.Safe_arithSafeArithU64.safe_sub val8
                          exit_balance
                      let cf9 ← core.result.Result.Insts.CoreOpsTry.branch r9
                      match cf9 with
                      | core.ops.control_flow.ControlFlow.Continue val9 =>
                        ok (core.result.Result.Ok (val6, val6, val9))
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          (Std.U64 × Std.U64 × Std.U64)
                          (core.convert.FromSame safe_arith.ArithError)
                          residual
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
                        safe_arith.ArithError) residual
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
                      safe_arith.ArithError) residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
                    safe_arith.ArithError) residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
                  safe_arith.ArithError) residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
                safe_arith.ArithError) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
              safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
            safe_arith.ArithError) residual
      else
        let r2 ←
          U64.Insts.Safe_arithSafeArithU64.safe_sub exit_balance_to_consume
            exit_balance
        let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          ok (core.result.Result.Ok (earliest_exit_epoch, earliest_exit_epoch,
            val2))
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
            safe_arith.ArithError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
        safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
      safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::registry_update::eligibility_step]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 92:0-105:1
    Visibility: public -/
def per_epoch_processing.registry_update.eligibility_step
  (fields : per_epoch_processing.registry_update.RegistryFields)
  (effective_balance : Std.U64) (current_epoch : Std.U64)
  (constants : per_epoch_processing.registry_update.RegistryConstants) :
  Result (core.result.Result
    per_epoch_processing.registry_update.RegistryFields safe_arith.ArithError)
  := do
  if fields.activation_eligibility_epoch = constants.far_future_epoch
  then
    if effective_balance >= constants.min_activation_balance
    then
      let r ← U64.Insts.Safe_arithSafeArithU64.safe_add current_epoch 1#u64
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        ok (core.result.Result.Ok
          { fields with activation_eligibility_epoch := val })
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          per_epoch_processing.registry_update.RegistryFields
          (core.convert.FromSame safe_arith.ArithError) residual
    else ok (core.result.Result.Ok fields)
  else ok (core.result.Result.Ok fields)

/-- [state_processing::per_epoch_processing::registry_update::ejection_step]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 108:0-137:1
    Visibility: public -/
def per_epoch_processing.registry_update.ejection_step
  (fields : per_epoch_processing.registry_update.RegistryFields)
  (effective_balance : Std.U64) (current_epoch : Std.U64)
  (total_active_balance : Std.U64)
  (constants : per_epoch_processing.registry_update.RegistryConstants) :
  Result (core.result.Result
    per_epoch_processing.registry_update.RegistryFields safe_arith.ArithError)
  := do
  let is_active ←
    if fields.activation_epoch <= current_epoch
    then ok (current_epoch < fields.exit_epoch)
    else ok false
  if is_active
  then
    if effective_balance <= constants.ejection_balance
    then
      if fields.exit_epoch = constants.far_future_epoch
      then
        let r ←
          per_epoch_processing.registry_update.compute_exit_epoch_and_update_churn
            effective_balance current_epoch fields.earliest_exit_epoch
            fields.exit_balance_to_consume total_active_balance constants
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let (exit_epoch, earliest_exit_epoch, exit_balance_to_consume) := val
          let r1 ←
            U64.Insts.Safe_arithSafeArithU64.safe_add exit_epoch
              constants.min_validator_withdrawability_delay
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            ok (core.result.Result.Ok
              {
                fields
                  with
                  exit_epoch,
                  withdrawable_epoch := val1,
                  earliest_exit_epoch,
                  exit_balance_to_consume
              })
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              per_epoch_processing.registry_update.RegistryFields
              (core.convert.FromSame safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            per_epoch_processing.registry_update.RegistryFields
            (core.convert.FromSame safe_arith.ArithError) residual
      else ok (core.result.Result.Ok fields)
    else ok (core.result.Result.Ok fields)
  else ok (core.result.Result.Ok fields)

/-- [state_processing::per_epoch_processing::registry_update::activation_step]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 140:0-154:1
    Visibility: public -/
def per_epoch_processing.registry_update.activation_step
  (fields : per_epoch_processing.registry_update.RegistryFields)
  (current_epoch : Std.U64) (finalized_epoch : Std.U64)
  (constants : per_epoch_processing.registry_update.RegistryConstants) :
  Result (core.result.Result
    per_epoch_processing.registry_update.RegistryFields safe_arith.ArithError)
  := do
  if fields.activation_eligibility_epoch <= finalized_epoch
  then
    if fields.activation_epoch = constants.far_future_epoch
    then
      let r ←
        per_epoch_processing.registry_update.compute_activation_exit_epoch
          current_epoch constants.max_seed_lookahead
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        ok (core.result.Result.Ok { fields with activation_epoch := val })
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          per_epoch_processing.registry_update.RegistryFields
          (core.convert.FromSame safe_arith.ArithError) residual
    else ok (core.result.Result.Ok fields)
  else ok (core.result.Result.Ok fields)

/-- [state_processing::per_epoch_processing::registry_update::registry_update]:
    Source: 'consensus/state_processing/src/per_epoch_processing/registry_update.rs', lines 160:0-177:1
    Visibility: public -/
def per_epoch_processing.registry_update.registry_update
  (fields : per_epoch_processing.registry_update.RegistryFields)
  (effective_balance : Std.U64) (current_epoch : Std.U64)
  (finalized_epoch : Std.U64) (total_active_balance : Std.U64)
  (constants : per_epoch_processing.registry_update.RegistryConstants) :
  Result (core.result.Result
    per_epoch_processing.registry_update.RegistryFields safe_arith.ArithError)
  := do
  let r ←
    per_epoch_processing.registry_update.eligibility_step fields
      effective_balance current_epoch constants
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ←
      per_epoch_processing.registry_update.ejection_step val effective_balance
        current_epoch total_active_balance constants
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      per_epoch_processing.registry_update.activation_step val1 current_epoch
        finalized_epoch constants
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        per_epoch_processing.registry_update.RegistryFields
        (core.convert.FromSame safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      per_epoch_processing.registry_update.RegistryFields
      (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::rewards_penalties::flag_delta]:
    Source: 'consensus/state_processing/src/per_epoch_processing/rewards_penalties.rs', lines 11:0-37:1
    Visibility: public -/
def per_epoch_processing.rewards_penalties.flag_delta
  (base_reward : Std.U64) (weight : Std.U64) (is_participating : Bool)
  (is_head_flag : Bool) (is_in_inactivity_leak : Bool)
  (unslashed_participating_increments : Std.U64) (active_increments : Std.U64)
  :
  Result (core.result.Result (Std.U64 × Std.U64) safe_arith.ArithError)
  := do
  if is_participating
  then
    if is_in_inactivity_leak
    then ok (core.result.Result.Ok (0#u64, 0#u64))
    else
      let r ← U64.Insts.Safe_arithSafeArithU64.safe_mul base_reward weight
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let r1 ←
          U64.Insts.Safe_arithSafeArithU64.safe_mul val
            unslashed_participating_increments
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          let r2 ←
            U64.Insts.Safe_arithSafeArithU64.safe_mul active_increments
              types.core.consts.altair.WEIGHT_DENOMINATOR
          let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue val2 =>
            let r3 ← U64.Insts.Safe_arithSafeArithU64.safe_div val1 val2
            let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
            match cf3 with
            | core.ops.control_flow.ControlFlow.Continue val3 =>
              ok (core.result.Result.Ok (val3, 0#u64))
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                (Std.U64 × Std.U64) (core.convert.FromSame
                safe_arith.ArithError) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              (Std.U64 × Std.U64) (core.convert.FromSame
              safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
            residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
          residual
  else
    if is_head_flag
    then ok (core.result.Result.Ok (0#u64, 0#u64))
    else
      let r ← U64.Insts.Safe_arithSafeArithU64.safe_mul base_reward weight
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let r1 ←
          U64.Insts.Safe_arithSafeArithU64.safe_div val
            types.core.consts.altair.WEIGHT_DENOMINATOR
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          ok (core.result.Result.Ok (0#u64, val1))
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
            residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          (Std.U64 × Std.U64) (core.convert.FromSame safe_arith.ArithError)
          residual

/-- [state_processing::per_epoch_processing::rewards_penalties::inactivity_penalty]:
    Source: 'consensus/state_processing/src/per_epoch_processing/rewards_penalties.rs', lines 40:0-53:1
    Visibility: public -/
def per_epoch_processing.rewards_penalties.inactivity_penalty
  (effective_balance : Std.U64) (inactivity_score : Std.U64)
  (is_participating_target : Bool) (inactivity_score_bias : Std.U64)
  (inactivity_penalty_quotient : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  if is_participating_target
  then ok (core.result.Result.Ok 0#u64)
  else
    let r ←
      U64.Insts.Safe_arithSafeArithU64.safe_mul effective_balance
        inactivity_score
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let r1 ←
        U64.Insts.Safe_arithSafeArithU64.safe_mul inactivity_score_bias
          inactivity_penalty_quotient
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        U64.Insts.Safe_arithSafeArithU64.safe_div val val1
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::rewards_penalties::new_balance_after_rewards]:
    Source: 'consensus/state_processing/src/per_epoch_processing/rewards_penalties.rs', lines 59:0-121:1
    Visibility: public -/
def per_epoch_processing.rewards_penalties.new_balance_after_rewards
  (balance : Std.U64) (is_eligible : Bool) (base_reward : Std.U64)
  (effective_balance : Std.U64) (inactivity_score : Std.U64)
  (is_participating_source : Bool) (is_participating_target : Bool)
  (is_participating_head : Bool) (is_in_inactivity_leak : Bool)
  (source_increments : Std.U64) (target_increments : Std.U64)
  (head_increments : Std.U64) (active_increments : Std.U64)
  (inactivity_score_bias : Std.U64) (inactivity_penalty_quotient : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  if is_eligible
  then
    let r ←
      per_epoch_processing.rewards_penalties.flag_delta base_reward
        types.core.consts.altair.TIMELY_SOURCE_WEIGHT is_participating_source
        false is_in_inactivity_leak source_increments active_increments
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (source_reward, source_penalty) := val
      let r1 ←
        per_epoch_processing.rewards_penalties.flag_delta base_reward
          types.core.consts.altair.TIMELY_TARGET_WEIGHT is_participating_target
          false is_in_inactivity_leak target_increments active_increments
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (target_reward, target_penalty) := val1
        let r2 ←
          per_epoch_processing.rewards_penalties.flag_delta base_reward
            types.core.consts.altair.TIMELY_HEAD_WEIGHT is_participating_head
            true is_in_inactivity_leak head_increments active_increments
        let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let (head_reward, head_penalty) := val2
          let r3 ←
            per_epoch_processing.rewards_penalties.inactivity_penalty
              effective_balance inactivity_score is_participating_target
              inactivity_score_bias inactivity_penalty_quotient
          let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue val3 =>
            let r4 ←
              U64.Insts.Safe_arithSafeArithU64.safe_add source_reward
                target_reward
            let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue val4 =>
              let r5 ←
                U64.Insts.Safe_arithSafeArithU64.safe_add val4 head_reward
              let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
              match cf5 with
              | core.ops.control_flow.ControlFlow.Continue val5 =>
                let r6 ←
                  U64.Insts.Safe_arithSafeArithU64.safe_add source_penalty
                    target_penalty
                let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                match cf6 with
                | core.ops.control_flow.ControlFlow.Continue val6 =>
                  let r7 ←
                    U64.Insts.Safe_arithSafeArithU64.safe_add val6 head_penalty
                  let cf7 ← core.result.Result.Insts.CoreOpsTry.branch r7
                  match cf7 with
                  | core.ops.control_flow.ControlFlow.Continue val7 =>
                    let r8 ←
                      U64.Insts.Safe_arithSafeArithU64.safe_add val7 val3
                    let cf8 ← core.result.Result.Insts.CoreOpsTry.branch r8
                    match cf8 with
                    | core.ops.control_flow.ControlFlow.Continue val8 =>
                      let r9 ←
                        U64.Insts.Safe_arithSafeArithU64.safe_add balance val5
                      let cf9 ← core.result.Result.Insts.CoreOpsTry.branch r9
                      match cf9 with
                      | core.ops.control_flow.ControlFlow.Continue val9 =>
                        let i ← lift (core.num.U64.saturating_sub val9 val8)
                        ok (core.result.Result.Ok i)
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          Std.U64 (core.convert.FromSame safe_arith.ArithError)
                          residual
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        Std.U64 (core.convert.FromSame safe_arith.ArithError)
                        residual
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame safe_arith.ArithError)
                      residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame safe_arith.ArithError)
                    residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame safe_arith.ArithError)
                  residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  else ok (core.result.Result.Ok balance)

/-- [state_processing::per_epoch_processing::slashings_penalty::slashings_context]:
    Source: 'consensus/state_processing/src/per_epoch_processing/slashings_penalty.rs', lines 10:0-31:1
    Visibility: public -/
def per_epoch_processing.slashings_penalty.slashings_context
  (sum_slashings : Std.U64) (proportional_slashing_multiplier : Std.U64)
  (total_active_balance : Std.U64) (current_epoch : Std.U64)
  (epochs_per_slashings_vector : Std.U64)
  (effective_balance_increment : Std.U64) :
  Result (core.result.Result (Std.U64 × Std.U64 × Std.U64)
    safe_arith.ArithError)
  := do
  let r ←
    U64.Insts.Safe_arithSafeArithU64.safe_mul sum_slashings
      proportional_slashing_multiplier
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let adjusted_total_slashing_balance ←
      core.cmp.min core.cmp.OrdU64 val total_active_balance
    let r1 ←
      U64.Insts.Safe_arithSafeArithU64.safe_div epochs_per_slashings_vector
        2#u64
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r2 ← U64.Insts.Safe_arithSafeArithU64.safe_add current_epoch val1
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let r3 ←
          U64.Insts.Safe_arithSafeArithU64.safe_div total_active_balance
            effective_balance_increment
        let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
        match cf3 with
        | core.ops.control_flow.ControlFlow.Continue val3 =>
          let r4 ←
            U64.Insts.Safe_arithSafeArithU64.safe_div
              adjusted_total_slashing_balance val3
          let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
          match cf4 with
          | core.ops.control_flow.ControlFlow.Continue val4 =>
            ok (core.result.Result.Ok (adjusted_total_slashing_balance, val2,
              val4))
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
              safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
            safe_arith.ArithError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
          safe_arith.ArithError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
        safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Std.U64 × Std.U64 × Std.U64) (core.convert.FromSame
      safe_arith.ArithError) residual

/-- [state_processing::per_epoch_processing::slashings_penalty::new_balance_after_slashing]:
    Source: 'consensus/state_processing/src/per_epoch_processing/slashings_penalty.rs', lines 35:0-63:1
    Visibility: public -/
def per_epoch_processing.slashings_penalty.new_balance_after_slashing
  (balance : Std.U64) (slashed : Bool) (withdrawable_epoch : Std.U64)
  (effective_balance : Std.U64) (target_withdrawable_epoch : Std.U64)
  (adjusted_total_slashing_balance : Std.U64)
  (penalty_per_effective_balance_increment : Std.U64)
  (total_active_balance : Std.U64) (effective_balance_increment : Std.U64)
  (electra_enabled : Bool) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  if slashed
  then
    if target_withdrawable_epoch != withdrawable_epoch
    then ok (core.result.Result.Ok balance)
    else
      if electra_enabled
      then
        let r ←
          U64.Insts.Safe_arithSafeArithU64.safe_div effective_balance
            effective_balance_increment
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let r1 ←
            U64.Insts.Safe_arithSafeArithU64.safe_mul
              penalty_per_effective_balance_increment val
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            let i ← lift (core.num.U64.saturating_sub balance val1)
            ok (core.result.Result.Ok i)
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
      else
        let r ←
          U64.Insts.Safe_arithSafeArithU64.safe_div effective_balance
            effective_balance_increment
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let r1 ←
            U64.Insts.Safe_arithSafeArithU64.safe_mul val
              adjusted_total_slashing_balance
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            let r2 ←
              U64.Insts.Safe_arithSafeArithU64.safe_div val1
                total_active_balance
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ←
                U64.Insts.Safe_arithSafeArithU64.safe_mul val2
                  effective_balance_increment
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let i ← lift (core.num.U64.saturating_sub balance val3)
                ok (core.result.Result.Ok i)
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame safe_arith.ArithError)
                  residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  else ok (core.result.Result.Ok balance)

end state_processing
