import SlotScheduleProofs.Loops
import SlotScheduleProofs.Validate
import SlotScheduleProofs.Spec

/-!
# Correctness of the EIP-8198 slot duration schedule

`Generated.lean` is generated by Aeneas from `consensus/types/src/core/slot_duration_schedule.rs`
and `consensus/types/src/features/eip8198/validation.rs`.
`Spec.lean` states the time of a slot and the slot at a time over natural numbers. This file
proves the properties of the two Rust functions that convert between slots and times, and what
`validate_schedule` and `validate_slot_duration_changes` guarantee about a schedule.

The slot and time theorems assume `ScheduleOk` (see `Model.lean`). `validate_schedule_ok` proves
that a schedule that passes `validate_schedule` meets it. `validate_changes_ok` proves that a
schedule that passes `validate_slot_duration_changes` changes the slot duration only at the
EIP-8198 fork epoch.
-/

namespace SlotScheduleProofs

open Aeneas Aeneas.Std Aeneas.Std.WP Result types

/-! ## The walk is the direct definition -/

theorem timeAtSlot_eq_spec (schedule : Slice Entry) (spe genesis_time_ms : U64) (slot : Nat)
    (h : ScheduleOk schedule spe) :
    timeAtSlot schedule spe genesis_time_ms slot =
      specTimeAtSlot spe.val (schedulePairs schedule) genesis_time_ms.val slot := by
  have hfold : specTimeAtSlot spe.val (schedulePairs schedule) genesis_time_ms.val slot =
      ((entries schedule spe).foldl foldStep (genesis_time_ms.val, slot)).1 := by
    rw [specTimeAtSlot, entries_eq, List.foldl_map]
    rfl
  rw [hfold, h.entries_split, fold_eq_walkTime h.chain_top (Nat.zero_le _)]
  rfl

theorem slotAtTime_eq_spec (schedule : Slice Entry) (spe genesis_time_ms : U64) (time : Nat)
    (h : ScheduleOk schedule spe) :
    specSlotAtTime spe.val (schedulePairs schedule) genesis_time_ms.val time =
      if genesis_time_ms.val ≤ time then some (slotAtTime schedule spe genesis_time_ms time)
      else none := by
  have hT : ∀ x, specTimeAtSlot spe.val (schedulePairs schedule) genesis_time_ms.val x =
      timeAtSlot schedule spe genesis_time_ms x := fun x => (timeAtSlot_eq_spec _ _ _ _ h).symm
  have hsearch : specSlotAtTime spe.val (schedulePairs schedule) genesis_time_ms.val time =
      (entries schedule spe).findSome? (slotIn (timeAtSlot schedule spe genesis_time_ms) time) := by
    rw [specSlotAtTime, entries_eq, List.findSome?_map]
    congr 1
    funext p
    simp only [Function.comp_def, slotIn, hT]
  rw [hsearch]
  split
  · rename_i hg
    rw [h.entries_split]
    exact findSome_eq_walkSlot h.chain_top (fun x _ => rfl) hg
  · rename_i hg
    rw [List.findSome?_eq_none_iff]
    intro q _
    have : genesis_time_ms.val ≤ timeAtSlot schedule spe genesis_time_ms q.1 := by
      rw [timeAtSlot]; exact le_walkTime h.chain_top (Nat.zero_le _)
    simp only [slotIn]
    rw [if_neg (by omega)]

/-! ## Round trip -/

/-- When the time of `slot` fits in a `u64`, the slot at that time is `slot`. -/
theorem slot_at_time_at_slot (schedule : Slice Entry) (spe genesis_time_ms : U64)
    (slot : core.slot_epoch.Slot) (t : U64) (h : ScheduleOk schedule spe)
    (ht : core.slot_duration_schedule.compute_time_at_slot_ms schedule spe genesis_time_ms slot = ok (.Ok t)) :
    core.slot_duration_schedule.compute_slot_at_time_ms schedule spe genesis_time_ms t = ok (.Ok slot) := by
  have htv := compute_time_at_slot_ms_eq h ht
  have hc := h.chain_top
  have hge : genesis_time_ms.val ≤ t.val := by
    rw [htv, timeAtSlot]; exact le_walkTime hc (Nat.zero_le _)
  obtain ⟨slot', hs, hsv⟩ := compute_slot_at_time_ms_eq (time_ms := t) h hge
  rw [hs]
  have : slot'.val = slot.val := by
    rw [hsv, slotAtTime, htv, timeAtSlot]
    exact walk_round_trip hc (Nat.zero_le _)
  rw [UScalar.eq_of_val_eq this]

/-! ## Floor -/

/-- At or after genesis, the slot at `time_ms` starts at or before `time_ms`, and the next slot
    starts after `time_ms`. The start time of the slot always fits in a `u64`. When the start
    time of the next slot does not fit, `compute_time_at_slot_ms` returns an error for it. -/
theorem time_at_slot_at_time (schedule : Slice Entry) (spe genesis_time_ms time_ms : U64)
    (slot : core.slot_epoch.Slot) (h : ScheduleOk schedule spe)
    (htime : genesis_time_ms.val ≤ time_ms.val)
    (hs : core.slot_duration_schedule.compute_slot_at_time_ms schedule spe genesis_time_ms time_ms = ok (.Ok slot)) :
    (∃ t : U64, core.slot_duration_schedule.compute_time_at_slot_ms schedule spe genesis_time_ms slot = ok (.Ok t) ∧
      t.val ≤ time_ms.val) ∧
    ∀ next : core.slot_epoch.Slot, next.val = slot.val + 1 →
      ∀ t : U64, core.slot_duration_schedule.compute_time_at_slot_ms schedule spe genesis_time_ms next = ok (.Ok t) →
        time_ms.val < t.val := by
  obtain ⟨slot', hs', hsv⟩ := compute_slot_at_time_ms_eq (time_ms := time_ms) h htime
  rw [hs] at hs'
  cases hs'
  have hc := h.chain_top
  obtain ⟨hlo, hhi⟩ := walk_floor (t := genesis_time_ms.val) hc htime
  rw [← slotAtTime, ← hsv] at hlo hhi
  constructor
  · have hle : timeAtSlot schedule spe genesis_time_ms slot.val ≤ U64.max := by
      rw [timeAtSlot]; have := time_ms.hBounds; scalar_tac
    obtain ⟨t, ht, htv⟩ := compute_time_at_slot_ms_of_le h hle
    exact ⟨t, ht, by rw [htv, timeAtSlot]; exact hlo⟩
  · intro next hnext t ht
    rw [compute_time_at_slot_ms_eq h ht, hnext, timeAtSlot]
    exact hhi

/-! ## Totality -/

/-- At or after genesis, `compute_slot_at_time_ms` returns a slot. -/
theorem compute_slot_at_time_ms_total (schedule : Slice Entry) (spe genesis_time_ms time_ms : U64)
    (h : ScheduleOk schedule spe) (htime : genesis_time_ms.val ≤ time_ms.val) :
    ∃ slot, core.slot_duration_schedule.compute_slot_at_time_ms schedule spe genesis_time_ms time_ms = ok (.Ok slot) := by
  obtain ⟨slot, hs, -⟩ := compute_slot_at_time_ms_eq (time_ms := time_ms) h htime
  exact ⟨slot, hs⟩

/-- `compute_time_at_slot_ms` never panics. It returns an error exactly when the time of the slot
    does not fit in a `u64`. -/
theorem compute_time_at_slot_ms_err_iff (schedule : Slice Entry) (spe genesis_time_ms : U64)
    (slot : core.slot_epoch.Slot) (h : ScheduleOk schedule spe) :
    ∃ r, core.slot_duration_schedule.compute_time_at_slot_ms schedule spe genesis_time_ms slot = ok r ∧
      ((∃ e, r = .Err e) ↔
        U64.max < specTimeAtSlot spe.val (schedulePairs schedule) genesis_time_ms.val slot.val) := by
  rw [← timeAtSlot_eq_spec _ _ _ _ h]
  obtain ⟨r, hr, hp⟩ := spec_imp_exists (compute_time_at_slot_ms_walk schedule spe genesis_time_ms slot h)
  refine ⟨r, hr, ?_⟩
  rcases r with t | e
  · simp only at hp
    simp only [reduceCtorEq, exists_false, false_iff, not_lt]
    rw [← hp]; scalar_tac
  · simpa using hp

/-! ## `validate_schedule` -/

/-- A schedule that passes `validate_schedule` meets `ScheduleOk`, when it is non-empty, sorted
    newest first (`EpochSchedule::new` sorts it) and `slots_per_epoch` is positive. Its genesis entry has the
    genesis slot duration. -/
theorem validate_schedule_ok (schedule : Slice Entry) (genesis_slot_duration_ms spe : U64)
    (hv : features.eip8198.validation.validate_schedule schedule genesis_slot_duration_ms spe =
      ok (.Ok ()))
    (hne : 0 < schedule.length) (hspe : 0 < spe.val)
    (hsorted : ∀ j (h : j + 1 < schedule.length),
      schedule.val[j + 1].epoch.val ≤ (schedule.val[j]'(Nat.lt_of_succ_lt h)).epoch.val) :
    ScheduleOk schedule spe ∧
    (schedule.val.getLast?).map (·.slot_duration_ms) = some genesis_slot_duration_ms := by
  obtain ⟨hnodup, hdur, hfit, hgen⟩ := validate_facts schedule genesis_slot_duration_ms spe hv hne
  have hmem : ∀ e ∈ schedule.val, ∃ j, j < schedule.length ∧ schedule.val[j]? = some e := by
    intro e he
    obtain ⟨j, hj, hje⟩ := List.getElem_of_mem he
    exact ⟨j, hj, by rw [List.getElem?_eq_getElem hj, hje]⟩
  have hlast : schedule.val.getLast? = schedule.val[schedule.length - 1]? := List.getLast?_eq_getElem?
  refine ⟨⟨?_, ?_, ?_, ?_, hspe⟩, ?_⟩
  · rw [hlast]
    have := congrArg (Option.map Prod.fst) hgen
    simpa [Option.map_map] using this
  · intro j h
    have hle := hsorted j h
    have hne' := hnodup j h
    rw [List.getElem?_eq_getElem (Nat.lt_of_succ_lt h), List.getElem?_eq_getElem h] at hne'
    simp only [Option.map_some, ne_eq, Option.some.injEq] at hne'
    have : schedule.val[j + 1].epoch.val ≠ (schedule.val[j]'(Nat.lt_of_succ_lt h)).epoch.val := by
      intro heq; exact hne' (UScalar.eq_of_val_eq heq.symm)
    omega
  · intro e he
    obtain ⟨j, hj, hje⟩ := hmem e he
    exact Nat.pos_of_ne_zero (hdur j e hj hje).1
  · intro e he
    obtain ⟨j, hj, hje⟩ := hmem e he
    exact hfit j e hj hje
  · rw [hlast]
    have := congrArg (Option.map Prod.snd) hgen
    simpa [Option.map_map] using this

/-- A schedule that passes `validate_slot_duration_changes` has every entry after genesis at the
    EIP-8198 fork epoch. -/
theorem validate_changes_ok (schedule : Slice Entry) (fork : Option core.slot_epoch.Epoch)
    (hv : features.eip8198.validation.validate_slot_duration_changes schedule fork = ok (.Ok ())) :
    ∀ e ∈ schedule.val, e.epoch.val = 0 ∨ fork = some e.epoch := by
  intro e he
  obtain ⟨j, hj, hje⟩ := List.getElem_of_mem he
  exact validate_changes_facts schedule fork hv j e hj (by rw [List.getElem?_eq_getElem hj, hje])

/-! ## Against the direct definitions -/

/-- `compute_time_at_slot_ms` returns `specTimeAtSlot`, or an error when that value does not fit
    in a `u64`. -/
theorem compute_time_at_slot_ms_spec (schedule : Slice Entry) (spe genesis_time_ms : U64)
    (slot : core.slot_epoch.Slot) (h : ScheduleOk schedule spe) :
    core.slot_duration_schedule.compute_time_at_slot_ms schedule spe genesis_time_ms slot ⦃ r => match r with
      | .Ok t => t.val = specTimeAtSlot spe.val (schedulePairs schedule) genesis_time_ms.val slot.val
      | .Err _ => U64.max < specTimeAtSlot spe.val (schedulePairs schedule) genesis_time_ms.val slot.val ⦄ := by
  rw [← timeAtSlot_eq_spec _ _ _ _ h]
  exact compute_time_at_slot_ms_walk schedule spe genesis_time_ms slot h

/-- `compute_slot_at_time_ms` returns `specSlotAtTime`: a slot at or after genesis, and an error
    before genesis. -/
theorem compute_slot_at_time_ms_spec (schedule : Slice Entry) (spe genesis_time_ms time_ms : U64)
    (h : ScheduleOk schedule spe) :
    core.slot_duration_schedule.compute_slot_at_time_ms schedule spe genesis_time_ms time_ms ⦃ r =>
      (match r with | .Ok slot => some slot.val | .Err _ => none) =
        specSlotAtTime spe.val (schedulePairs schedule) genesis_time_ms.val time_ms.val ⦄ := by
  rw [slotAtTime_eq_spec _ _ _ _ h]
  split
  · rename_i hg
    apply spec_mono (compute_slot_at_time_ms_walk schedule spe genesis_time_ms time_ms h hg)
    rintro r ⟨slot, rfl, hs⟩
    simp [hs]
  · rename_i hg
    apply spec_mono (compute_slot_at_time_ms_before_genesis schedule spe genesis_time_ms time_ms h
      (by omega))
    rintro (slot | e) hr
    · exact hr.elim
    · rfl

end SlotScheduleProofs
