-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [types]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace types

/-- [core::fmt::{impl core::fmt::Display for str}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2981:4-2981:50
    Name pattern: [core::fmt::{core::fmt::Display<str>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Display<str>}::fmt"]
axiom Str.Insts.CoreFmtDisplay.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [core::fmt::{impl core::fmt::Display for str}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2980:0-2980:20
    Name pattern: [core::fmt::Display<str>] -/
@[reducible, rust_trait_impl "core::fmt::Display<str>"]
def Str.Insts.CoreFmtDisplay : core.fmt.Display Str := {
  fmt := Str.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [core::fmt::num::imp::{impl core::fmt::Display for u64}]
    Source: '/rustc/library/core/src/fmt/num.rs', lines 134:8-134:39
    Name pattern: [core::fmt::Display<u64>] -/
@[reducible, rust_trait_impl "core::fmt::Display<u64>"]
def U64.Insts.CoreFmtDisplay : core.fmt.Display Std.U64 := {
  fmt := core.fmt.num.imp.DisplayU64.fmt
}

/-- [core::hint::must_use]:
    Source: '/rustc/library/core/src/hint.rs', lines 613:0-613:39
    Name pattern: [core::hint::must_use]
    Visibility: public -/
@[rust_fun "core::hint::must_use"]
axiom core.hint.must_use {T : Type} : T → Result T

/-- [core::num::{u64}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2584:8-2584:60
    Name pattern: [core::num::{u64}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{u64}::saturating_mul"]
axiom core.num.U64.saturating_mul : Std.U64 → Std.U64 → Result Std.U64

/-- [core::option::{core::option::Option<T>}::is_some_and]:
    Source: '/rustc/library/core/src/option.rs', lines 659:4-659:96
    Name pattern: [core::option::{core::option::Option<@T>}::is_some_and]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::is_some_and"]
def core.option.Option.is_some_and
  {T : Type} {T1 : Type} (opsfunctionFnOnceT1TupleTBoolInst :
  core.ops.function.FnOnce T1 T Bool) (self : Option T) (f : T1) :
  Result Bool
  := do
  let (b, b1) ←
    match self with
    | none => ok (false, true)
    | some x =>
      do
      let b2 ← opsfunctionFnOnceT1TupleTBoolInst.call_once f x
      ok (b2, false)
  if b1
  then ok b
  else ok b

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1158:4-1160:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
def core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) (self : Option T) (f : F) :
  Result (Option U)
  := do
  let (o, b) ←
    match self with
    | none => ok (none, true)
    | some x =>
      do
      let t ← opsfunctionFnOnceFTupleTUInst.call_once f x
      ok (some t, false)
  if b
  then ok o
  else ok o

/-- [alloc::fmt::format]:
    Source: '/rustc/library/alloc/src/fmt.rs', lines 649:0-649:52
    Name pattern: [alloc::fmt::format]
    Visibility: public -/
@[rust_fun "alloc::fmt::format"]
axiom alloc.fmt.format : core.fmt.Arguments → Result String

/-- [alloc::string::{impl alloc::string::ToString for T}::to_string]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2930:4-2930:33
    Name pattern: [alloc::string::{alloc::string::ToString<@T>}::to_string]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::ToString<@T>}::to_string"]
axiom alloc.string.ToString.Blanket.to_string
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result String

/-- [safe_arith::ArithError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 75:0-75:19
    Name pattern: [safe_arith::ArithError]
    Visibility: public -/
@[discriminant isize, rust_type "safe_arith::ArithError"]
inductive safe_arith.ArithError where
| Overflow : safe_arith.ArithError
| DivisionByZero : safe_arith.ArithError

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 140:12-140:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_add]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_add"]
def U64.Insts.Safe_arithSafeArithU64.safe_add
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_add self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 145:12-145:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_sub]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_sub"]
def U64.Insts.Safe_arithSafeArithU64.safe_sub
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_sub self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_mul]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 150:12-150:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_mul]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_mul"]
def U64.Insts.Safe_arithSafeArithU64.safe_mul
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_mul self other)
  core.option.Option.ok_or o safe_arith.ArithError.Overflow

/-- [safe_arith::{impl safe_arith::SafeArith<u64> for u64}::safe_div]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/safe_arith-0.1.0/src/lib.rs', lines 155:12-155:59
    Name pattern: [safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_div]
    Visibility: public -/
@[rust_fun "safe_arith::{safe_arith::SafeArith<u64, u64>}::safe_div"]
def U64.Insts.Safe_arithSafeArithU64.safe_div
  (self : Std.U64) (other : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let o ← lift (U64.checked_div self other)
  core.option.Option.ok_or o safe_arith.ArithError.DivisionByZero

/-- [types::core::slot_epoch::Epoch]
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 32:0-32:65
    Visibility: public -/
@[reducible]
def core.slot_epoch.Epoch := Std.U64

/-- [types::core::slot_duration_schedule::SlotDurationScheduleEntry]
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 12:0-16:1
    Visibility: public -/
structure core.slot_duration_schedule.SlotDurationScheduleEntry where
  epoch : core.slot_epoch.Epoch
  slot_duration_ms : Std.U64

/-- [types::core::slot_epoch::Slot]
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 27:0-27:64
    Visibility: public -/
@[reducible]
def core.slot_epoch.Slot := Std.U64

/-- [types::core::slot_epoch::{types::core::slot_epoch::Slot}::as_u64]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 16:12-18:13
    Visibility: public -/
def core.slot_epoch.Slot.as_u64
  (self : core.slot_epoch.Slot) : Result Std.U64 := do
  ok self

/-- [types::core::slot_epoch::{impl core::convert::From<u64> for types::core::slot_epoch::Slot}::from]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 4:12-6:13
    Visibility: public -/
def core.slot_epoch.Slot.Insts.CoreConvertFromU64.from
  (n : Std.U64) : Result core.slot_epoch.Slot := do
  ok n

/-- [types::core::slot_epoch::{types::core::slot_epoch::Epoch}::start_slot]:
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 70:4-72:5
    Visibility: public -/
def core.slot_epoch.Epoch.start_slot
  (self : core.slot_epoch.Epoch) (slots_per_epoch : Std.U64) :
  Result core.slot_epoch.Slot
  := do
  let i ← core.num.U64.saturating_mul self slots_per_epoch
  core.slot_epoch.Slot.Insts.CoreConvertFromU64.from i

/-- [types::core::slot_epoch::{impl core::convert::From<types::core::slot_epoch::Slot> for u64}::from]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 10:12-12:13
    Visibility: public -/
def U64.Insts.CoreConvertFromSlot.from
  («from» : core.slot_epoch.Slot) : Result Std.U64 := do
  ok «from»

/-- Trait implementation: [types::core::slot_epoch::{impl core::convert::From<types::core::slot_epoch::Slot> for u64}]
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 9:8-13:9 -/
@[reducible]
def U64.Insts.CoreConvertFromSlot : core.convert.From Std.U64
  core.slot_epoch.Slot := {
  «from» := U64.Insts.CoreConvertFromSlot.from
}

/-- [types::core::slot_epoch::{types::core::slot_epoch::Slot}::new]:
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 45:4-47:5
    Visibility: public -/
def core.slot_epoch.Slot.new
  (slot : Std.U64) : Result core.slot_epoch.Slot := do
  ok slot

/-- [types::core::slot_epoch::{types::core::slot_epoch::Slot}::{impl core::ops::function::FnOnce<(u64,), types::core::slot_epoch::Slot> for types::core::slot_epoch::{types::core::slot_epoch::Slot}::new}::call_once]:
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 45:4-47:5
    Visibility: public -/
def P.Insts.CoreOpsFunctionFnOnceTupleU64Slot.call_once
  (state : Std.U64 → Result core.slot_epoch.Slot) (args : Std.U64) :
  Result core.slot_epoch.Slot
  := do
  core.slot_epoch.Slot.new args

/-- Trait implementation: [types::core::slot_epoch::{types::core::slot_epoch::Slot}::{impl core::ops::function::FnOnce<(u64,), types::core::slot_epoch::Slot> for types::core::slot_epoch::{types::core::slot_epoch::Slot}::new}]
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 45:4-47:5 -/
@[reducible]
def P.Insts.CoreOpsFunctionFnOnceTupleU64Slot : core.ops.function.FnOnce
  (Std.U64 → Result core.slot_epoch.Slot) Std.U64 core.slot_epoch.Slot := {
  call_once := P.Insts.CoreOpsFunctionFnOnceTupleU64Slot.call_once
}

/-- [types::core::slot_epoch::{impl safe_arith::SafeArith<types::core::slot_epoch::Slot> for types::core::slot_epoch::Slot}::safe_sub]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 74:12-79:13
    Visibility: public -/
def core.slot_epoch.Slot.Insts.Safe_arithSafeArithSlot.safe_sub
  (self : core.slot_epoch.Slot) (other : core.slot_epoch.Slot) :
  Result (core.result.Result core.slot_epoch.Slot safe_arith.ArithError)
  := do
  let i ← core.convert.IntoFrom.into U64.Insts.CoreConvertFromSlot other
  let o ← lift (U64.checked_sub self i)
  let o1 ←
    core.option.Option.map P.Insts.CoreOpsFunctionFnOnceTupleU64Slot o
      (core.slot_epoch.Slot.new)
  core.option.Option.ok_or o1 safe_arith.ArithError.Overflow

/-- [types::core::slot_duration_schedule::time_after_slots_ms]:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 127:0-139:1 -/
def core.slot_duration_schedule.time_after_slots_ms
  (start_time_ms : Std.U64) (start_slot : core.slot_epoch.Slot)
  (end_slot : core.slot_epoch.Slot) (slot_duration_ms : Std.U64) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let r ←
    core.slot_epoch.Slot.Insts.Safe_arithSafeArithSlot.safe_sub end_slot
      start_slot
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← core.slot_epoch.Slot.as_u64 val
    let r1 ← U64.Insts.Safe_arithSafeArithU64.safe_mul i slot_duration_ms
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      U64.Insts.Safe_arithSafeArithU64.safe_add start_time_ms val1
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame safe_arith.ArithError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [types::core::slot_duration_schedule::compute_time_at_slot_ms]: loop body 0:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 67:4-85:5 -/
@[rust_loop_body]
def core.slot_duration_schedule.compute_time_at_slot_ms_loop.body
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (slot : core.slot_epoch.Slot) (index : Std.Usize)
  (start_slot : core.slot_epoch.Slot) (start_time_ms : Std.U64)
  (slot_duration_ms : Std.U64) :
  Result (ControlFlow (Std.Usize × core.slot_epoch.Slot × Std.U64 × Std.U64)
    (core.slot_epoch.Slot × Std.U64 × Std.U64 × Bool))
  := do
  if index > 0#usize
  then
    let index1 ← lift (core.num.Usize.saturating_sub index 1#usize)
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index1
    match o with
    | none => ok (done (start_slot, start_time_ms, slot_duration_ms, false))
    | some entry =>
      let entry_slot ←
        core.slot_epoch.Epoch.start_slot entry.epoch slots_per_epoch
      let i ← core.slot_epoch.Slot.as_u64 slot
      let i1 ← core.slot_epoch.Slot.as_u64 entry_slot
      if i <= i1
      then ok (done (start_slot, start_time_ms, slot_duration_ms, false))
      else
        let r ←
          core.slot_duration_schedule.time_after_slots_ms start_time_ms
            start_slot entry_slot slot_duration_ms
        match r with
        | core.result.Result.Ok entry_time_ms =>
          ok (cont (index1, entry_slot, entry_time_ms, entry.slot_duration_ms))
        | core.result.Result.Err _ =>
          ok (done (start_slot, start_time_ms, slot_duration_ms, true))
  else ok (done (start_slot, start_time_ms, slot_duration_ms, false))

/-- [types::core::slot_duration_schedule::compute_time_at_slot_ms]: loop 0:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 67:4-85:5 -/
@[rust_loop]
def core.slot_duration_schedule.compute_time_at_slot_ms_loop
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (slot : core.slot_epoch.Slot) (index : Std.Usize)
  (start_slot : core.slot_epoch.Slot) (start_time_ms : Std.U64)
  (slot_duration_ms : Std.U64) :
  Result (core.slot_epoch.Slot × Std.U64 × Std.U64 × Bool)
  := do
  loop
    (fun (index1, start_slot1, start_time_ms1, slot_duration_ms1) =>
      core.slot_duration_schedule.compute_time_at_slot_ms_loop.body schedule
      slots_per_epoch slot index1 start_slot1 start_time_ms1 slot_duration_ms1)
    (index, start_slot, start_time_ms, slot_duration_ms)

/-- [types::core::slot_duration_schedule::compute_time_at_slot_ms]:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 55:0-90:1 -/
def core.slot_duration_schedule.compute_time_at_slot_ms
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (genesis_time_ms : Std.U64)
  (slot : core.slot_epoch.Slot) :
  Result (core.result.Result Std.U64 safe_arith.ArithError)
  := do
  let i := Slice.len schedule
  let index ← lift (core.num.Usize.saturating_sub i 1#usize)
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
      core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index
  let r ← core.option.Option.ok_or o safe_arith.ArithError.Overflow
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let start_slot ←
      core.slot_epoch.Epoch.start_slot val.epoch slots_per_epoch
    let (start_slot1, start_time_ms, slot_duration_ms, overflow) ←
      core.slot_duration_schedule.compute_time_at_slot_ms_loop schedule
        slots_per_epoch slot index start_slot genesis_time_ms
        val.slot_duration_ms
    if overflow
    then ok (core.result.Result.Err safe_arith.ArithError.Overflow)
    else
      core.slot_duration_schedule.time_after_slots_ms start_time_ms start_slot1
        slot slot_duration_ms
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame safe_arith.ArithError) residual

/-- [types::core::slot_epoch::{impl safe_arith::SafeArith<u64> for types::core::slot_epoch::Slot}::safe_add]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 67:12-72:13
    Visibility: public -/
def core.slot_epoch.Slot.Insts.Safe_arithSafeArithU64.safe_add
  (self : core.slot_epoch.Slot) (other : Std.U64) :
  Result (core.result.Result core.slot_epoch.Slot safe_arith.ArithError)
  := do
  let i ← core.convert.IntoFrom.into (core.convert.FromSame Std.U64) other
  let o ← lift (U64.checked_add self i)
  let o1 ←
    core.option.Option.map P.Insts.CoreOpsFunctionFnOnceTupleU64Slot o
      (core.slot_epoch.Slot.new)
  core.option.Option.ok_or o1 safe_arith.ArithError.Overflow

/-- [types::core::slot_duration_schedule::compute_slot_at_time_ms]: loop body 0:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 103:4-120:5 -/
@[rust_loop_body]
def core.slot_duration_schedule.compute_slot_at_time_ms_loop.body
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (time_ms : Std.U64) (index : Std.Usize)
  (start_slot : core.slot_epoch.Slot) (start_time_ms : Std.U64)
  (slot_duration_ms : Std.U64) :
  Result (ControlFlow (Std.Usize × core.slot_epoch.Slot × Std.U64 × Std.U64)
    (core.slot_epoch.Slot × Std.U64 × Std.U64))
  := do
  if index > 0#usize
  then
    let index1 ← lift (core.num.Usize.saturating_sub index 1#usize)
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
        core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index1
    match o with
    | none => ok (done (start_slot, start_time_ms, slot_duration_ms))
    | some entry =>
      let entry_slot ←
        core.slot_epoch.Epoch.start_slot entry.epoch slots_per_epoch
      let r ←
        core.slot_duration_schedule.time_after_slots_ms start_time_ms
          start_slot entry_slot slot_duration_ms
      match r with
      | core.result.Result.Ok entry_time_ms =>
        if time_ms < entry_time_ms
        then ok (done (start_slot, start_time_ms, slot_duration_ms))
        else
          ok (cont (index1, entry_slot, entry_time_ms, entry.slot_duration_ms))
      | core.result.Result.Err _ =>
        ok (done (start_slot, start_time_ms, slot_duration_ms))
  else ok (done (start_slot, start_time_ms, slot_duration_ms))

/-- [types::core::slot_duration_schedule::compute_slot_at_time_ms]: loop 0:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 103:4-120:5 -/
@[rust_loop]
def core.slot_duration_schedule.compute_slot_at_time_ms_loop
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (time_ms : Std.U64) (index : Std.Usize)
  (start_slot : core.slot_epoch.Slot) (start_time_ms : Std.U64)
  (slot_duration_ms : Std.U64) :
  Result (core.slot_epoch.Slot × Std.U64 × Std.U64)
  := do
  loop
    (fun (index1, start_slot1, start_time_ms1, slot_duration_ms1) =>
      core.slot_duration_schedule.compute_slot_at_time_ms_loop.body schedule
      slots_per_epoch time_ms index1 start_slot1 start_time_ms1
      slot_duration_ms1)
    (index, start_slot, start_time_ms, slot_duration_ms)

/-- [types::core::slot_duration_schedule::compute_slot_at_time_ms]:
    Source: 'consensus/types/src/core/slot_duration_schedule.rs', lines 92:0-125:1 -/
def core.slot_duration_schedule.compute_slot_at_time_ms
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (genesis_time_ms : Std.U64) (time_ms : Std.U64) :
  Result (core.result.Result core.slot_epoch.Slot safe_arith.ArithError)
  := do
  let i := Slice.len schedule
  let index ← lift (core.num.Usize.saturating_sub i 1#usize)
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
      core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index
  let r ← core.option.Option.ok_or o safe_arith.ArithError.Overflow
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let start_slot ←
      core.slot_epoch.Epoch.start_slot val.epoch slots_per_epoch
    let (start_slot1, start_time_ms, slot_duration_ms) ←
      core.slot_duration_schedule.compute_slot_at_time_ms_loop schedule
        slots_per_epoch time_ms index start_slot genesis_time_ms
        val.slot_duration_ms
    let r1 ← U64.Insts.Safe_arithSafeArithU64.safe_sub time_ms start_time_ms
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r2 ←
        U64.Insts.Safe_arithSafeArithU64.safe_div val1 slot_duration_ms
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        core.slot_epoch.Slot.Insts.Safe_arithSafeArithU64.safe_add start_slot1
          val2
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          core.slot_epoch.Slot (core.convert.FromSame safe_arith.ArithError)
          residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        core.slot_epoch.Slot (core.convert.FromSame safe_arith.ArithError)
        residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      core.slot_epoch.Slot (core.convert.FromSame safe_arith.ArithError)
      residual

/-- [types::core::slot_epoch::{impl core::cmp::PartialEq<types::core::slot_epoch::Epoch> for types::core::slot_epoch::Epoch}::eq]:
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 30:31-30:40
    Visibility: public -/
def core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch.eq
  (self : core.slot_epoch.Epoch) (other : core.slot_epoch.Epoch) :
  Result Bool
  := do
  ok (self = other)

/-- Trait implementation: [types::core::slot_epoch::{impl core::cmp::PartialEq<types::core::slot_epoch::Epoch> for types::core::slot_epoch::Epoch}]
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 30:31-30:40 -/
@[reducible]
impl_def core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch : core.cmp.PartialEq
  core.slot_epoch.Epoch core.slot_epoch.Epoch := {
  eq := core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch.eq
  ne := core.cmp.PartialEq.ne.trait_default
    core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch
}

/-- [types::core::slot_epoch::{types::core::slot_epoch::Epoch}::new]:
    Source: 'consensus/types/src/core/slot_epoch.rs', lines 61:4-63:5
    Visibility: public -/
def core.slot_epoch.Epoch.new
  (epoch : Std.U64) : Result core.slot_epoch.Epoch := do
  ok epoch

/-- [types::core::slot_epoch::{types::core::slot_epoch::Epoch}::as_u64]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 16:12-18:13
    Visibility: public -/
def core.slot_epoch.Epoch.as_u64
  (self : core.slot_epoch.Epoch) : Result Std.U64 := do
  ok self

/-- [types::core::slot_epoch::{impl core::fmt::Display for types::core::slot_epoch::Epoch}::fmt]:
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 226:12-228:13
    Visibility: public -/
def core.slot_epoch.Epoch.Insts.CoreFmtDisplay.fmt
  (self : core.slot_epoch.Epoch) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let a ← core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay self
  let a1 ←
    core.fmt.Arguments.new (Array.make 2#usize [ 192#u8, 0#u8 ])
      (Array.make 1#usize [ a ])
  core.fmt.Formatter.write_fmt f a1

/-- Trait implementation: [types::core::slot_epoch::{impl core::fmt::Display for types::core::slot_epoch::Epoch}]
    Source: 'consensus/types/src/core/slot_epoch_macros.rs', lines 225:8-229:9 -/
@[reducible]
def core.slot_epoch.Epoch.Insts.CoreFmtDisplay : core.fmt.Display
  core.slot_epoch.Epoch := {
  fmt := core.slot_epoch.Epoch.Insts.CoreFmtDisplay.fmt
}

/-- [types::features::eip8198::validation::validate_schedule]: loop body 0:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 18:4-27:5 -/
@[rust_loop_body]
def features.eip8198.validation.validate_schedule_loop0.body
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (index : Std.Usize) (previous_epoch : Option core.slot_epoch.Epoch) :
  Result (ControlFlow (Std.Usize × (Option core.slot_epoch.Epoch)) (Option
    core.slot_epoch.Epoch))
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
      core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index
  match o with
  | none => ok (done none)
  | some entry =>
    match previous_epoch with
    | none =>
      let index1 ← lift (core.num.Usize.saturating_add index 1#usize)
      ok (cont (index1, some entry.epoch))
    | some epoch =>
      let b ←
        core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch.eq epoch entry.epoch
      if b
      then ok (done previous_epoch)
      else
        let index1 ← lift (core.num.Usize.saturating_add index 1#usize)
        ok (cont (index1, some entry.epoch))

/-- [types::features::eip8198::validation::validate_schedule]: loop 0:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 18:4-27:5 -/
@[rust_loop]
def features.eip8198.validation.validate_schedule_loop0
  (index : Std.Usize)
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (previous_epoch : Option core.slot_epoch.Epoch) :
  Result (Option core.slot_epoch.Epoch)
  := do
  loop
    (fun (index1, previous_epoch1) =>
      features.eip8198.validation.validate_schedule_loop0.body schedule index1
      previous_epoch1)
    (index, previous_epoch)

/-- [types::features::eip8198::validation::validate_schedule]: loop body 1:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 33:4-39:5 -/
@[rust_loop_body]
def features.eip8198.validation.validate_schedule_loop1.body
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (index : Std.Usize) :
  Result (ControlFlow Std.Usize (Option (Std.U64 × core.slot_epoch.Epoch)))
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
      core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index
  match o with
  | none => ok (done none)
  | some entry =>
    if entry.slot_duration_ms = 0#u64
    then ok (done (some (entry.slot_duration_ms, entry.epoch)))
    else
      let i ← entry.slot_duration_ms % 1000#u64
      if i != 0#u64
      then ok (done (some (entry.slot_duration_ms, entry.epoch)))
      else
        let index1 ← lift (core.num.Usize.saturating_add index 1#usize)
        ok (cont index1)

/-- [types::features::eip8198::validation::validate_schedule]: loop 1:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 33:4-39:5 -/
@[rust_loop]
def features.eip8198.validation.validate_schedule_loop1
  (index : Std.Usize)
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry) :
  Result (Option (Std.U64 × core.slot_epoch.Epoch))
  := do
  loop
    (fun index1 => features.eip8198.validation.validate_schedule_loop1.body
      schedule index1)
    index

/-- [types::features::eip8198::validation::validate_schedule]: loop body 2:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 48:4-54:5 -/
@[rust_loop_body]
def features.eip8198.validation.validate_schedule_loop2.body
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) (index : Std.Usize) :
  Result (ControlFlow Std.Usize (Option core.slot_epoch.Epoch))
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
      core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index
  match o with
  | none => ok (done none)
  | some entry =>
    let i ← core.slot_epoch.Epoch.as_u64 entry.epoch
    let o1 ← lift (U64.checked_mul i slots_per_epoch)
    let b := core.option.Option.is_none o1
    if b
    then ok (done (some entry.epoch))
    else
      let index1 ← lift (core.num.Usize.saturating_add index 1#usize)
      ok (cont index1)

/-- [types::features::eip8198::validation::validate_schedule]: loop 2:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 48:4-54:5 -/
@[rust_loop]
def features.eip8198.validation.validate_schedule_loop2
  (index : Std.Usize)
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (slots_per_epoch : Std.U64) :
  Result (Option core.slot_epoch.Epoch)
  := do
  loop
    (fun index1 => features.eip8198.validation.validate_schedule_loop2.body
      schedule slots_per_epoch index1)
    index

/-- [types::features::eip8198::validation::validate_schedule]:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 7:0-73:1 -/
def features.eip8198.validation.validate_schedule
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (genesis_slot_duration_ms : Std.U64) (slots_per_epoch : Std.U64) :
  Result (core.result.Result Unit String)
  := do
  let b ← core.slice.Slice.is_empty schedule
  if b
  then ok (core.result.Result.Ok ())
  else
    let duplicate_epoch ←
      features.eip8198.validation.validate_schedule_loop0 0#usize schedule none
    match duplicate_epoch with
    | none =>
      let invalid_duration ←
        features.eip8198.validation.validate_schedule_loop1 0#usize schedule
      match invalid_duration with
      | none =>
        let invalid_start_slot ←
          features.eip8198.validation.validate_schedule_loop2 0#usize schedule
            slots_per_epoch
        match invalid_start_slot with
        | none =>
          let i := Slice.len schedule
          let i1 ← lift (core.num.Usize.saturating_sub i 1#usize)
          let o ←
            core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
              core.slot_duration_schedule.SlotDurationScheduleEntry) schedule
              i1
          match o with
          | none =>
            let s ←
              alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay
                (toStr "the first entry must be at the genesis epoch")
            ok (core.result.Result.Err s)
          | some entry =>
            let e ← core.slot_epoch.Epoch.new 0#u64
            let b1 ←
              core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch.eq entry.epoch
                e
            if b1
            then
              if entry.slot_duration_ms != genesis_slot_duration_ms
              then
                let a ←
                  core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay
                    entry.slot_duration_ms
                let a1 ←
                  core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay
                    genesis_slot_duration_ms
                let a2 ←
                  core.fmt.Arguments.new
                    (Array.make 60#usize [
                      22#u8, 103#u8, 101#u8, 110#u8, 101#u8, 115#u8, 105#u8,
                      115#u8, 32#u8, 115#u8, 108#u8, 111#u8, 116#u8, 32#u8,
                      100#u8, 117#u8, 114#u8, 97#u8, 116#u8, 105#u8, 111#u8,
                      110#u8, 32#u8, 192#u8, 33#u8, 32#u8, 100#u8, 111#u8,
                      101#u8, 115#u8, 32#u8, 110#u8, 111#u8, 116#u8, 32#u8,
                      109#u8, 97#u8, 116#u8, 99#u8, 104#u8, 32#u8, 83#u8,
                      76#u8, 79#u8, 84#u8, 95#u8, 68#u8, 85#u8, 82#u8, 65#u8,
                      84#u8, 73#u8, 79#u8, 78#u8, 95#u8, 77#u8, 83#u8, 32#u8,
                      192#u8, 0#u8
                      ]) (Array.make 2#usize [ a, a1 ])
                let s ← alloc.fmt.format a2
                let s1 ← core.hint.must_use s
                ok (core.result.Result.Err s1)
              else ok (core.result.Result.Ok ())
            else
              let s ←
                alloc.string.ToString.Blanket.to_string
                  Str.Insts.CoreFmtDisplay (toStr
                  "the first entry must be at the genesis epoch")
              ok (core.result.Result.Err s)
        | some epoch =>
          let a ←
            core.fmt.rt.Argument.new_display
              core.slot_epoch.Epoch.Insts.CoreFmtDisplay epoch
          let a1 ←
            core.fmt.Arguments.new
              (Array.make 50#usize [
                24#u8, 116#u8, 104#u8, 101#u8, 32#u8, 115#u8, 116#u8, 97#u8,
                114#u8, 116#u8, 32#u8, 115#u8, 108#u8, 111#u8, 116#u8, 32#u8,
                111#u8, 102#u8, 32#u8, 101#u8, 112#u8, 111#u8, 99#u8, 104#u8,
                32#u8, 192#u8, 22#u8, 32#u8, 100#u8, 111#u8, 101#u8, 115#u8,
                32#u8, 110#u8, 111#u8, 116#u8, 32#u8, 102#u8, 105#u8, 116#u8,
                32#u8, 105#u8, 110#u8, 32#u8, 97#u8, 32#u8, 117#u8, 54#u8,
                52#u8, 0#u8
                ]) (Array.make 1#usize [ a ])
          let s ← alloc.fmt.format a1
          let s1 ← core.hint.must_use s
          ok (core.result.Result.Err s1)
      | some p =>
        let (slot_duration_ms, epoch) := p
        let a ←
          core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay
            slot_duration_ms
        let a1 ←
          core.fmt.rt.Argument.new_display
            core.slot_epoch.Epoch.Insts.CoreFmtDisplay epoch
        let a2 ←
          core.fmt.Arguments.new
            (Array.make 65#usize [
              14#u8, 115#u8, 108#u8, 111#u8, 116#u8, 32#u8, 100#u8, 117#u8,
              114#u8, 97#u8, 116#u8, 105#u8, 111#u8, 110#u8, 32#u8, 192#u8,
              10#u8, 32#u8, 97#u8, 116#u8, 32#u8, 101#u8, 112#u8, 111#u8,
              99#u8, 104#u8, 32#u8, 192#u8, 35#u8, 32#u8, 105#u8, 115#u8,
              32#u8, 110#u8, 111#u8, 116#u8, 32#u8, 97#u8, 32#u8, 112#u8,
              111#u8, 115#u8, 105#u8, 116#u8, 105#u8, 118#u8, 101#u8, 32#u8,
              109#u8, 117#u8, 108#u8, 116#u8, 105#u8, 112#u8, 108#u8, 101#u8,
              32#u8, 111#u8, 102#u8, 32#u8, 49#u8, 48#u8, 48#u8, 48#u8, 0#u8
              ]) (Array.make 2#usize [ a, a1 ])
        let s ← alloc.fmt.format a2
        let s1 ← core.hint.must_use s
        ok (core.result.Result.Err s1)
    | some epoch =>
      let a ←
        core.fmt.rt.Argument.new_display
          core.slot_epoch.Epoch.Insts.CoreFmtDisplay epoch
      let a1 ←
        core.fmt.Arguments.new
          (Array.make 30#usize [
            27#u8, 109#u8, 117#u8, 108#u8, 116#u8, 105#u8, 112#u8, 108#u8,
            101#u8, 32#u8, 101#u8, 110#u8, 116#u8, 114#u8, 105#u8, 101#u8,
            115#u8, 32#u8, 102#u8, 111#u8, 114#u8, 32#u8, 101#u8, 112#u8,
            111#u8, 99#u8, 104#u8, 32#u8, 192#u8, 0#u8
            ]) (Array.make 1#usize [ a ])
      let s ← alloc.fmt.format a1
      let s1 ← core.hint.must_use s
      ok (core.result.Result.Err s1)

/-- [types::features::eip8198::validation::validate_slot_duration_changes::closure]
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 83:47-83:85 -/
@[reducible]
def features.eip8198.validation.validate_slot_duration_changes.closure :=
  core.slot_duration_schedule.SlotDurationScheduleEntry

/-- [types::features::eip8198::validation::validate_slot_duration_changes::{impl core::ops::function::FnOnce<(types::core::slot_epoch::Epoch,), bool> for types::features::eip8198::validation::validate_slot_duration_changes::closure<'_0>}::call_once]:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 83:47-83:85 -/
def
  features.eip8198.validation.validate_slot_duration_changes.closure.Insts.CoreOpsFunctionFnOnceTupleEpochBool.call_once
  (c : features.eip8198.validation.validate_slot_duration_changes.closure)
  (tupled_args : core.slot_epoch.Epoch) :
  Result Bool
  := do
  core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch.eq tupled_args c.epoch

/-- Trait implementation: [types::features::eip8198::validation::validate_slot_duration_changes::{impl core::ops::function::FnOnce<(types::core::slot_epoch::Epoch,), bool> for types::features::eip8198::validation::validate_slot_duration_changes::closure<'_0>}]
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 83:47-83:85 -/
@[reducible]
def
  features.eip8198.validation.validate_slot_duration_changes.closure.Insts.CoreOpsFunctionFnOnceTupleEpochBool
  : core.ops.function.FnOnce
  features.eip8198.validation.validate_slot_duration_changes.closure
  core.slot_epoch.Epoch Bool := {
  call_once :=
    features.eip8198.validation.validate_slot_duration_changes.closure.Insts.CoreOpsFunctionFnOnceTupleEpochBool.call_once
}

/-- [types::features::eip8198::validation::validate_slot_duration_changes]: loop body 0:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 81:4-89:5 -/
@[rust_loop_body]
def features.eip8198.validation.validate_slot_duration_changes_loop.body
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (eip8198_fork_epoch : Option core.slot_epoch.Epoch) (index : Std.Usize) :
  Result (ControlFlow Std.Usize (Option core.slot_epoch.Epoch))
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
      core.slot_duration_schedule.SlotDurationScheduleEntry) schedule index
  match o with
  | none => ok (done none)
  | some entry =>
    let e ← core.slot_epoch.Epoch.new 0#u64
    let b ←
      core.cmp.PartialEq.ne.trait_default
        core.slot_epoch.Epoch.Insts.CoreCmpPartialEqEpoch entry.epoch e
    if b
    then
      let b1 ←
        core.option.Option.is_some_and
          features.eip8198.validation.validate_slot_duration_changes.closure.Insts.CoreOpsFunctionFnOnceTupleEpochBool
          eip8198_fork_epoch entry
      if b1
      then
        let index1 ← lift (core.num.Usize.saturating_add index 1#usize)
        ok (cont index1)
      else ok (done (some entry.epoch))
    else
      let index1 ← lift (core.num.Usize.saturating_add index 1#usize)
      ok (cont index1)

/-- [types::features::eip8198::validation::validate_slot_duration_changes]: loop 0:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 81:4-89:5 -/
@[rust_loop]
def features.eip8198.validation.validate_slot_duration_changes_loop
  (index : Std.Usize)
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (eip8198_fork_epoch : Option core.slot_epoch.Epoch) :
  Result (Option core.slot_epoch.Epoch)
  := do
  loop
    (fun index1 =>
      features.eip8198.validation.validate_slot_duration_changes_loop.body
      schedule eip8198_fork_epoch index1)
    index

/-- [types::features::eip8198::validation::validate_slot_duration_changes]:
    Source: 'consensus/types/src/features/eip8198/validation.rs', lines 75:0-97:1 -/
def features.eip8198.validation.validate_slot_duration_changes
  (schedule : Slice core.slot_duration_schedule.SlotDurationScheduleEntry)
  (eip8198_fork_epoch : Option core.slot_epoch.Epoch) :
  Result (core.result.Result Unit String)
  := do
  let unscheduled_change ←
    features.eip8198.validation.validate_slot_duration_changes_loop 0#usize
      schedule eip8198_fork_epoch
  match unscheduled_change with
  | none => ok (core.result.Result.Ok ())
  | some epoch =>
    let a ←
      core.fmt.rt.Argument.new_display
        core.slot_epoch.Epoch.Insts.CoreFmtDisplay epoch
    let a1 ←
      core.fmt.Arguments.new
        (Array.make 72#usize [
          34#u8, 116#u8, 104#u8, 101#u8, 32#u8, 115#u8, 108#u8, 111#u8, 116#u8,
          32#u8, 100#u8, 117#u8, 114#u8, 97#u8, 116#u8, 105#u8, 111#u8, 110#u8,
          32#u8, 99#u8, 104#u8, 97#u8, 110#u8, 103#u8, 101#u8, 32#u8, 97#u8,
          116#u8, 32#u8, 101#u8, 112#u8, 111#u8, 99#u8, 104#u8, 32#u8, 192#u8,
          34#u8, 32#u8, 105#u8, 115#u8, 32#u8, 110#u8, 111#u8, 116#u8, 32#u8,
          97#u8, 116#u8, 32#u8, 116#u8, 104#u8, 101#u8, 32#u8, 69#u8, 73#u8,
          80#u8, 45#u8, 56#u8, 49#u8, 57#u8, 56#u8, 32#u8, 102#u8, 111#u8,
          114#u8, 107#u8, 32#u8, 101#u8, 112#u8, 111#u8, 99#u8, 104#u8, 0#u8
          ]) (Array.make 1#usize [ a ])
    let s ← alloc.fmt.format a1
    let s1 ← core.hint.must_use s
    ok (core.result.Result.Err s1)

end types
